### ISSUE TITLE
Mocking modules not working on Windows 10

### ISSUE THREAD

**Issue by pYr0x** [vitest-dev/vitest#1210]
### Describe the bug

i had trouble with mocking a module. the module will not be mocked. so i found a test on vitest test's.
https://github.com/vitest-dev/vitest/blob/main/test/core/test/hoist-import.test.ts
i tried to reproduce the test in my project and it failed. so i tried to create a stackblitz and it worked... !?

### Reproduction

stackblitz with working test:
https://stackblitz.com/edit/vitest-dev-vitest-ma89ey

Github Repo that i used locally on my windows 10 machine (and it failed)
https://github.com/pYr0x/vitest_mock

i used pnpm and npm. both not working for my locally

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 3.17 GB / 15.85 GB
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.50)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vite: latest => 2.9.6
    vitest: latest => 0.10.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Well, we also run tests on windows in our CI 🤔 
@userquin can you help with this issue?

**Comment by pYr0x** [comment]
Hey guys, any progress with this issue?
@sheremet-va @userquin

**Comment by pYr0x** [comment]
@sheremet-va i found the problem.
i have a whitespace in my directoryname. my project is under: 
`C:/Users/xxx/Desktop/Neuer Ordner/vitest_mock/`
the regex for parsing the stacktrace in https://github.com/vitest-dev/vitest/blob/306b54503af332a70d5918b39ee60c5944212bcc/packages/vitest/src/utils/source-map.ts#L24-L25 does not correct match.

a stacktrace line `line at C:/Users/xxx/Desktop/Neuer Ordner/vitest_mock/test/foo.test.js:3:26` will be matched into 
```
{
  method: 'C:/Users/xxx/Desktop/Neuer',
  file: 'Ordner/vitest_mock/test/foo.test.js',
  line: 3,
  column: 26
}
```

**Comment by pYr0x** [comment]
mocking if working correctly. the problem is the whitespace in the directory name

**Comment by userquin** [comment]
@pYr0x I'll check it in a few minutes...

**Comment by userquin** [comment]
@sheremet-va the mocking is not working on Windows when the path has some spaces, the same project just renaming from `vitest_mock_issue_1210` to `vitest mock issue 1210` fails.

On project with spaces in the path, the suite mocks are just: `{ '../src/timeout.ts': [Function (anonymous)] }` while on the project without spaces returns : `{ '/src/timeout.ts': [Function (anonymous)] }`

Just download the ZIP from the original and rename it: the problem should be on macosx/linux.

We have something strange using latest on vitest dep, I cannot find the regex for stackFnCallRE but the version is 0.10.0.

**Comment by userquin** [comment]
it seems not working on other OS when there are spaces on the path, I talk with `@sheremet-va` and we're working on a fix, the importer is not being resolved correctly

@pYr0x your regex works but we'll use similar approach from here: https://www.npmjs.com/package/error-stack-parser

The last source entry will be fixed on the PR:

```shell
{
  method: '',
  file: 'F:/work/projects/quini/GitHub/issue-repro/vitest mock issue 1210/test/foo.test.ts',
  line: '3',
  column: '30',
  source: '    at F:/work/projects/quini/GitHub/issue-repro/vitest mock issue 1210/test/foo.test.ts:3:30'
}
```

**Comment by pYr0x** [comment]
@userquin is this bug fixed?

**Comment by sheremet-va** [comment]
> @userquin is this bug fixed?

Should be fixed in #1457
