### ISSUE TITLE
Vite trying to bundle unused dependencies in library mode

### ISSUE THREAD

**Issue by brielov** [vitest-dev/vitest#1216]
### Describe the bug

Hi, I have a project I'm trying to migrate to vite and vitest called [typed](https://github.com/brielov/typed).

The problem is when I try to build the project this happens:

```
❯ npm run build

> typed@4.0.0 build
> tsc && vite build

vite v2.9.6 building for production...
✓ 121 modules transformed.
'promises' is not exported by __vite-browser-external, imported by node_modules/local-pkg/dist/shared.mjs
file: node_modules/local-pkg/dist/shared.mjs:62:13
60: import process2 from "node:process";
61: import path from "node:path";
62: import fs, { promises as fsPromises } from "node:fs";
                 ^
63:
64: // node_modules/.pnpm/yocto-queue@1.0.0/node_modules/yocto-queue/index.js
error during build:
Error: 'promises' is not exported by __vite-browser-external, imported by node_modules/local-pkg/dist/shared.mjs
    at error (node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (node_modules/rollup/dist/shared/rollup.js:12521:16)
    at Module.traceVariable (node_modules/rollup/dist/shared/rollup.js:12879:29)
    at ModuleScope.findVariable (node_modules/rollup/dist/shared/rollup.js:11509:39)
    at FunctionScope.findVariable (node_modules/rollup/dist/shared/rollup.js:6477:38)
    at ChildScope.findVariable (node_modules/rollup/dist/shared/rollup.js:6477:38)
    at MemberExpression.bind (node_modules/rollup/dist/shared/rollup.js:8706:49)
    at ConditionalExpression.bind (node_modules/rollup/dist/shared/rollup.js:5342:23)
    at VariableDeclarator.bind (node_modules/rollup/dist/shared/rollup.js:5342:23)
    at VariableDeclaration.bind (node_modules/rollup/dist/shared/rollup.js:5338:31)
```

The project has no external nor internal dependencies. It doesn't even uses promises. It uses vitest's inline tests, but vite is supposed to eliminate dead code. Here's my `vite.config.ts`.

```ts
/// <reference types="vitest" />

import dts from "vite-plugin-dts";
import { defineConfig } from "vite";
import { resolve } from "path";

export default defineConfig({
  plugins: [dts()],
  build: {
    target: "es2020",
    lib: {
      entry: resolve(__dirname, "src/index.ts"),
      name: "typed",
      formats: ["es", "umd"],
      fileName: "index",
    },
  },
  define: {
    "import.meta.vitest": false,
  },
  test: {
    includeSource: ["src/**/*.ts"],
    watch: false,
  },
});

```

### Reproduction

https://github.com/brielov/typed/tree/feat/vite

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
    Memory: 142.69 MB / 8.00 GB
    Shell: 5.1.16 - /opt/homebrew/bin/bash
  Binaries:
    Node: 16.14.2 - ~/Library/Caches/fnm_multishells/71650_1651325050772/bin/node
    Yarn: 1.22.18 - ~/Library/Caches/fnm_multishells/71650_1651325050772/bin/yarn
    npm: 8.5.0 - ~/Library/Caches/fnm_multishells/71650_1651325050772/bin/npm
  Browsers:
    Brave Browser: 101.1.38.109
    Chrome: 100.0.4896.127
    Safari: 15.4
    Safari Technology Preview: 15.4
  npmPackages:
    vite: ^2.9.6 => 2.9.6 
    vitest: ^0.10.0 => 0.10.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by techtolentino** [comment]
Curious - how was this resolved?
