### ISSUE TITLE
Installing vitest into existing mono repo throws: "local" cannot be used as a mode name 

### ISSUE THREAD

**Issue by fyyyyy** [vitest-dev/vitest#1616]
### Describe the bug

vitest 0.17.1 was installed into a package of an existing lerna mono repo. It was installed to replace jest, which is still installed in this package.

```
     ...
    "jest": "27.5.1",
    "jest-cli": "27.5.1",
    "lint-staged": "12.3.5",
    "onchange": "7.1.0",
    "ts-jest": "27.1.3",
    "typescript": "4.6.2",
    "vitest": "0.17.1"
  }
```

It doesnt matter which vitest.config is supplied, it always throws this error. The project doesnt even have an .env file that it could possibly try to load.

```js
npm run vitest
> @project/cli@3.2.1 vitest /workspaces/myproject/packages/cli
> vitest


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: "local" cannot be used as a mode name because it conflicts with the .local postfix for .env files.
    at loadEnv (/workspaces/myproject/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:61989:15)
    at resolveConfig (/workspaces/myproject/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:61493:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async createServer (/workspaces/myproject/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:60080:20)
    at async createVitest (file:///workspaces/myproject/node_modules/vitest/dist/chunk-vite-node-externalize.0fc8ed68.mjs:11003:18)
    at async startVitest (file:///workspaces/myproject/node_modules/vitest/dist/chunk-vite-node-externalize.0fc8ed68.mjs:11090:15)
    at async CAC.start (file:///workspaces/myproject/node_modules/vitest/dist/cli.mjs:666:9)
```

It seems that vitest is calling vite loadEnv, the relevant line in vite is https://github.com/vitejs/vite/blob/v2.9.14/packages/vite/src/node/config.ts#L1061

### Reproduction

needs reproduction

### System Info

```shell
docker VS code dev container alpine in WSL2
FROM --platform=linux/amd64 node:14.16.1-alpine
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fyyyyy** [comment]
Ok, found the issue, our devContainer docker defined NODE_ENV as local, which is not allowed by vite.

  "containerEnv": {
    "NODE_ENV": "local",
