### ISSUE TITLE
Error: No "exports" main defined in package.json

### ISSUE THREAD

**Issue by madhank93** [vitest-dev/vitest#1827]
### Describe the bug

Unable to run tests. Getting the following error ```Error: No "exports" main defined in /home/madhank/Desktop/git/learn-dsa/node_modules/vitest/package.json```

Stack trace:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  bin/src/data-structures/single-linked-list/single-linked-list.spec.js [ bin/src/data-structures/single-linked-list/single-linked-list.spec.js ]
Error: No "exports" main defined in /home/madhank/Desktop/git/learn-dsa/node_modules/vitest/package.json
 ❯ src/data-structures/single-linked-list/single-linked-list.spec.ts:1:0

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
RangeError: Invalid count value
 ❯ generateCodeFrame node_modules/vitest/dist/chunk-vite-node-externalize.0791f2ed.mjs:10294:35
 ❯ node_modules/vitest/dist/chunk-vite-node-externalize.0791f2ed.mjs:10168:50
 ❯ printStack node_modules/vitest/dist/chunk-vite-node-externalize.0791f2ed.mjs:10258:32
 ❯ printError node_modules/vitest/dist/chunk-vite-node-externalize.0791f2ed.mjs:10163:3
 ❯ processTicksAndRejections node:internal/process/task_queues:96:5
 ❯ DefaultReporter.printTaskErrors node_modules/vitest/dist/chunk-vite-node-externalize.0791f2ed.mjs:7488:7
 ❯ DefaultReporter.reportSummary node_modules/vitest/dist/chunk-vite-node-externalize.0791f2ed.mjs:7434:7
 ❯ DefaultReporter.onFinished node_modules/vitest/dist/chunk-vite-node-externalize.0791f2ed.mjs:7293:5
 ❯ DefaultReporter.onFinished node_modules/vitest/dist/chunk-vite-node-externalize.0791f2ed.mjs:7627:5
```

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/madhank/Desktop/git/learn-dsa/node_modules/vitest/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:693:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/madhank/Desktop/git/learn-dsa/src/data-structures/single-linked-list/single-linked-list.spec.ts:1:1) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Reproduction

Repo - https://github.com/madhank93/learn-dsa and run the command ```npm run test```

### System Info

```shell
System:
    OS: Linux 5.14 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 9.78 GB / 15.40 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 103.0
  npmPackages:
    vitest: ^0.18.0 => 0.18.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yacinehmito** [comment]
We managed to silence the error by removing this line:

https://github.com/vitest-dev/vitest/blob/main/packages/vitest/package.json#L28

**Comment by madhank93** [comment]
@yacinehmito Upgrading the package didn't work for me as well. So I delete the entire repo and cloned it again. Not sure this is the right thing to do.

**Comment by yacinehmito** [comment]
On our end, the culprit was `eslint-import-resolver-alias`. Its last version is 4 years old, at a time where ESM support was not a topic.
Node's resolution logic assumes that it's running in CommonJS, so it was looking for a `require` field in the relevant `export` in `package.json`. There was none, so it crashed with this error.
We fixed the problem by using `eslint-importe-resolver-customer-alias`, which is more recent and specifies to Node's resolver that ESM is used, so that it looks at the `import` field instead.

**Comment by fthebaud** [comment]
I was having similar issues, error messages like that:
```
1:1   error    Resolve error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/fthebaud/Workspace/de.idnow.vi.web.frontend/node_modules/vitest/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:671:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at findModulePath (/home/fthebaud/Workspace/de.idnow.vi.web.frontend/node_modules/eslint-import-resolver-alias/index.js:99:27)
    at Object.exports.resolve (/home/fthebaud/Workspace/de.idnow.vi.web.frontend/node_modules/eslint-import-resolver-alias/index.js:75:10)
    at v2 (/home/fthebaud/Workspace/de.idnow.vi.web.frontend/node_modules/eslint-module-utils/resolve.js:116:23)
    at withResolver (/home/fthebaud/Workspace/de.idnow.vi.web.frontend/node_modules/eslint-module-utils/resolve.js:121:14)
    at fullResolve (/home/fthebaud/Workspace/de.idnow.vi.web.frontend/node_modules/eslint-module-utils/resolve.js:138:22)  import/namespace
```

As suggested by @yacinehmito, replacing `eslint-import-resolver-alias` by the more recent `eslint-import-resolver-custom-alias` fixed the problem.
