### ISSUE TITLE
Error:  callback.apply is not a function

### ISSUE THREAD

**Issue by masx200** [vitest-dev/vitest#2250]
### Describe the bug

```
vitest run

Error:  
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error:  callback.apply is not a function
  at exec (node_modules/_@antfu_utils@0.6.1@@antfu/utils/dist/index.mjs:358:16)
  at wrapper (node_modules/_@antfu_utils@0.6.1@@antfu/utils/dist/index.mjs:3[9](https://github.com/masx200/ant-colony-algorithm-function-test/actions/runs/3232400654/jobs/5583048040#step:6:10)8:9)
  at Object.scanDirs (node_modules/_unplugin-auto-import@0.11.4@unplugin-auto-import/dist/chunk-JSTOHG77.js:188:5)
  at Context.buildStart (node_modules/_unplugin-auto-import@0.11.4@unplugin-auto-import/dist/chunk-JSTOHG77.js:261:17)
  at hookParallel (node_modules/_vite@3.2.2@vite/dist/node/chunks/dep-c842e491.js:4[10](https://github.com/masx200/ant-colony-algorithm-function-test/actions/runs/3232400654/jobs/5583048040#step:6:11)52:47)
  at Object.buildStart (node_modules/_vite@3.2.2@vite/dist/node/chunks/dep-c842e491.js:41326:19)
  at createVitest (node_modules/_vitest@0.24.4@vitest/dist/chunk-vite-node-externalize.e66d46f6.js:10668:34)
  at async startVitest (node_modules/_vitest@0.24.4@vitest/dist/chunk-vite-node-externalize.e66d46f6.js:10773:15)
  at async start (node_modules/_vitest@0.24.4@vitest/dist/cli.js:685:9)
  at async CAC.run (node_modules/_vitest@0.24.4@vitest/dist/cli.js:671:3)
Error:  


Error: Process completed with exit code 1.
```

### Reproduction

https://github.com/masx200/ant-colony-algorithm-function-test/actions/runs/3232400654/jobs/5583048040

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.65 GB / 7.85 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.675.0), Chromium (107.0.1418.26)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue: ^3.0.3 => 3.2.0
    vite: 3.2.0 => 3.2.0
    vitest: ^0.24.0 => 0.24.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You have an old version of unplugin-auto-imports
