### ISSUE TITLE
Cannot install vitest 0.27.1

### ISSUE THREAD

**Issue by fruddq** [vitest-dev/vitest#2678]
### Describe the bug

Cannot install latest vitest.

### Reproduction

```fish
❯ node -v
v18.13.0

❯ npm init -y
Wrote to /tmp/projectTest/package.json:

{
  "name": "projecttest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "esbuild": "^0.17.0",
    "vitest": "^0.27.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

❯ pnpm i vitest@0.27.1 -D
Packages: +51
+++++++++++++++++++++++++++++++++++++++++++++++++++
node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild: Running postinstall script, failed in 107ms
.../esbuild@0.16.17/node_modules/esbuild postinstall$ node install.js
│ /tmp/projectTest/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/install.js:130
│     throw new Error(`Expected ${JSON.stringify("0.16.17")} but got ${JSON.stringify(stdout)}`);
│           ^
│ Error: Expected "0.16.17" but got "0.17.0"
│     at validateBinaryVersion (/tmp/projectTest/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/install.js:130:11)
│     at /tmp/projectTest/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/install.js:281:5
│ Node.js v18.13.0
└─ Failed in 108ms at /tmp/projectTest/node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild
node_modules/.pnpm/esbuild@0.17.0/node_modules/esbuild: Running postinstall script, done in 109ms
 ELIFECYCLE  Command failed with exit code 1.
Progress: resolved 94, reused 51, downloaded 0, added 0
```

### System Info

```shell
❯ npx envinfo --system --npmPackages '{vitest,vite,@vitejs/*}' --binaries --browsers
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: Linux 6.1 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 8.23 GB / 15.53 GB
    Container: Yes
    Shell: 3.5.1 - /bin/fish
  Binaries:
    Node: 18.13.0 - ~/.asdf/installs/nodejs/lts/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.3 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Firefox: 108.0.2
  npmPackages:
    vitest: ^0.27.1 => 0.27.1 
```
```


### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by beckend** [comment]
I have the same thing with npm:
```bash
$ npm i -D vitest
npm ERR! code 1
npm ERR! path /tmp/dsadsadas/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! /tmp/dsadsadas/node_modules/esbuild/install.js:130
npm ERR!     throw new Error(`Expected ${JSON.stringify("0.16.17")} but got ${JSON.stringify(stdout)}`);
npm ERR!           ^
npm ERR!
npm ERR! Error: Expected "0.16.17" but got "0.17.0"
npm ERR!     at validateBinaryVersion (/tmp/dsadsadas/node_modules/esbuild/install.js:130:11)
npm ERR!     at /tmp/dsadsadas/node_modules/esbuild/install.js:281:5
npm ERR!
npm ERR! Node.js v18.13.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2023-01-16T08_11_45_643Z-debug-0.log
```

**Comment by sheremet-va** [comment]
It feels like a esbuild issue, and not Vitest? Vitest doesn't even define esbuild version, Vite does.

**Comment by beckend** [comment]
You are probably right, installed vite failed witht the same error.

**Comment by beckend** [comment]
But this also means that we cannot install vitest now.

**Comment by beckend** [comment]
Found the solution here: https://github.com/evanw/esbuild/issues/2865
```bash
export ESBUILD_BINARY_PATH=
npm i
```
