### ISSUE TITLE
vite-node is using incorrect node_modules when resolving local dependencies in a monorepo

### ISSUE THREAD

**Issue by jgoux** [vitest-dev/vitest#2787]
### Describe the bug

In a pnpm monorepo, I have a package `@acme/app` depending on another package `@acme/sdk`.

When executing my `@acme/app` package with `vite-node`, it doesn't use `@acme/sdk` own `node_modules` to resolve `find-up` dependency, it uses the one in root `node_modules` which is used internally by `@changesets/cli`.

[tsx](https://github.com/esbuild-kit/tsx) handles the resolution correctly but doesn't support TS paths alias that I want to use in my monorepo (thanks to `vite-tsconfig-paths` it's possible with `vite-node`!) 😄

```bash
➜  ts-runner git:(main) DEBUG=vite-node:* pnpm --filter app start:vite-node

> @acme/app@0.0.0 start:vite-node /Users/jgoux/Documents/code/ts-runner/packages/app
> vite-node src/index.ts

  vite-node:server:request /@vite/env +0ms
  vite-node:client:execute /@vite/env +0ms
  vite-node:server:request /Users/jgoux/Documents/code/ts-runner/packages/app/src/index.ts +26ms
  vite-node:client:execute /Users/jgoux/Documents/code/ts-runner/packages/app/src/index.ts +9ms
  vite-node:server:request /Users/jgoux/Documents/code/ts-runner/packages/sdk/src/index.ts +10ms
  vite-node:client:execute /Users/jgoux/Documents/code/ts-runner/packages/sdk/src/index.ts +9ms
  vite-node:server:request /Users/jgoux/Documents/code/ts-runner/packages/sdk/src/service/logger.ts +8ms
  vite-node:client:execute /Users/jgoux/Documents/code/ts-runner/packages/sdk/src/service/logger.ts +8ms
  vite-node:client:native /Users/jgoux/Documents/code/ts-runner/node_modules/chalk/index.js +0ms
  vite-node:server:request /Users/jgoux/Documents/code/ts-runner/packages/sdk/src/config/env.ts +25ms
  vite-node:client:execute /Users/jgoux/Documents/code/ts-runner/packages/sdk/src/config/env.ts +20ms
  vite-node:client:native /Users/jgoux/Documents/code/ts-runner/node_modules/find-up/index.js +15ms
/Users/jgoux/Documents/code/ts-runner/packages/sdk/src/config/env.ts:4
  await __vite_ssr_import_0__.pathExists(".env");
                              ^

TypeError: __vite_ssr_import_0__.pathExists is not a function
    at Module.getEnv (/Users/jgoux/Documents/code/ts-runner/packages/sdk/src/config/env.ts:4:9)
    at Module.logVersion (/Users/jgoux/Documents/code/ts-runner/packages/sdk/src/service/logger.ts:5:51)
    at /Users/jgoux/Documents/code/ts-runner/packages/app/src/index.ts:3:1
    at ViteNodeRunner.directRequest (file:///Users/jgoux/Documents/code/ts-runner/node_modules/vite-node/dist/client.mjs:308:5)
    at ViteNodeRunner.cachedRequest (file:///Users/jgoux/Documents/code/ts-runner/node_modules/vite-node/dist/client.mjs:156:14)
    at ViteNodeRunner.executeFile (file:///Users/jgoux/Documents/code/ts-runner/node_modules/vite-node/dist/client.mjs:133:12)
    at CAC.run (file:///Users/jgoux/Documents/code/ts-runner/node_modules/vite-node/dist/cli.mjs:64:5)
```

The line:
```
vite-node:client:native /Users/jgoux/Documents/code/ts-runner/node_modules/find-up/index.js +15ms
```

Should be:
```
vite-node:client:native /Users/jgoux/Documents/code/ts-runner/packages/sdk/node_modules/find-up/index.js +15ms
```

### Reproduction

https://github.com/jgoux/ts-runners-monorepo

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 94.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/Library/pnpm/node
    npm: 8.19.3 - ~/Library/pnpm/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 108.0.2
    Safari: 16.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jgoux** [comment]
After investigating my issue, it's solved by https://github.com/vitest-dev/vitest/pull/2777

In my case the importer being another package in my monorepo than the one calling `node-vite`, having the `importee` to `undefined` caused the resolution to look up from the package calling `node-vite`, which resolved `node_modules/find-up` instead of `packages/sdk/node_modules/find-up`.
