### ISSUE TITLE
[vite-node] error transforming template literals with source map magic string

### ISSUE THREAD

**Issue by Tanimodori** [vitest-dev/vitest#2918]
### Describe the bug

`vite-node` will transform the following code

```ts
export function foo(src: string): string {
  return `//# sourceMappingURL=data:application/json;base64,${src}`;
}
```

into

```js
// /home/projects/vitest-dev-vitest-dq6zze/foo.ts
function foo(src) {
  return `
}
Object.defineProperty(__vite_ssr_exports__, "foo", { enumerable: true, configurable: true, get(){ return foo }});

//# sourceMappingSource=vite-node
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkFBQU8sU0FBUyxJQUFJLEtBQXFCO0FBQ3ZDLFNBQU8scURBQXFEO0FBQzlEO2lIQUFBIiwibmFtZXMiOltdLCJzb3VyY2VzIjpbIi9ob21lL3Byb2plY3RzL3ZpdGVzdC1kZXYtdml0ZXN0LWRxNnp6ZS9mb28udHMiXSwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IGZ1bmN0aW9uIGZvbyhzcmM6IHN0cmluZyk6IHN0cmluZyB7XHJcbiAgcmV0dXJuIGAvLyMgc291cmNlTWFwcGluZ1VSTD1kYXRhOmFwcGxpY2F0aW9uL2pzb247YmFzZTY0LCR7c3JjfWA7XHJcbn1cclxuIl0sImZpbGUiOiIvaG9tZS9wcm9qZWN0cy92aXRlc3QtZGV2LXZpdGVzdC1kcTZ6emUvZm9vLnRzIn0=
```

The backtick is missing so it will resulting in `SyntaxError: Unexpected end of input` in run-time.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-dq6zze?file=foo.ts

Reproduction steps:

1. `VITE_NODE_DEBUG_DUMP=true && vite-node ./foo.ts`

```bash
[vite-node] [debug] dump modules to /home/projects/vitest-dev-vitest-dq6zze/.vite-node/dump
SyntaxError: Unexpected end of input
    at __global_eval__ (https://vitestdevvitestdq6zze-ytrg.w-credentialless.staticblitz.com/blitz.fc57b779eff411414c7b91114df9b720faaf721b.js:1:267)
    at _0x3c1c8c (https://vitestdevvitestdq6zze-ytrg.w-credentialless.staticblitz.com/blitz.fc57b779eff411414c7b91114df9b720faaf721b.js:15:145824)
    at Script.runInThisContext (https://vitestdevvitestdq6zze-ytrg.w-credentialless.staticblitz.com/blitz.fc57b779eff411414c7b91114df9b720faaf721b.js:15:144645)
    at Script.runInThisContext (https://vitestdevvitestdq6zze-ytrg.w-credentialless.staticblitz.com/blitz.fc57b779eff411414c7b91114df9b720faaf721b.js:6:338067)
    at Object.runInThisContext (https://vitestdevvitestdq6zze-ytrg.w-credentialless.staticblitz.com/blitz.fc57b779eff411414c7b91114df9b720faaf721b.js:6:340777)
    at ViteNodeRunner.directRequest (file://file:///home/projects/vitest-dev-vitest-dq6zze/node_modules/vite-node/dist/client.mjs:324:32)
    at ViteNodeRunner.cachedRequest (file://file:///home/projects/vitest-dev-vitest-dq6zze/node_modules/vite-node/dist/client.mjs:173:14)
    at ViteNodeRunner.executeFile (file://file:///home/projects/vitest-dev-vitest-dq6zze/node_modules/vite-node/dist/client.mjs:150:12)
    at CAC.run (file://file:///home/projects/vitest-dev-vitest-dq6zze/node_modules/vite-node/dist/cli.mjs:81:5)
```

2. `cat ~/projects/vitest-dev-vitest-dq6zze/.vite-node/dump/_home_projects_vitest-dev-vitest-dq6zze_foo_ts-756022366.js` (Note that the hash may change. Use auto-completion for correct filename.)

```
// /home/projects/vitest-dev-vitest-dq6zze/foo.ts
function foo(src) {
  return `
}
Object.defineProperty(__vite_ssr_exports__, "foo", { enumerable: true, configurable: true, get(){ return foo }});

//# sourceMappingSource=vite-node
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkFBQU8sU0FBUyxJQUFJLEtBQXFCO0FBQ3ZDLFNBQU8scURBQXFEO0FBQzlEO2lIQUFBIiwibmFtZXMiOltdLCJzb3VyY2VzIjpbIi9ob21lL3Byb2plY3RzL3ZpdGVzdC1kZXYtdml0ZXN0LWRxNnp6ZS9mb28udHMiXSwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IGZ1bmN0aW9uIGZvbyhzcmM6IHN0cmluZyk6IHN0cmluZyB7XHJcbiAgcmV0dXJuIGAvLyMgc291cmNlTWFwcGluZ1VSTD1kYXRhOmFwcGxpY2F0aW9uL2pzb247YmFzZTY0LCR7c3JjfWA7XHJcbn1cclxuIl0sImZpbGUiOiIvaG9tZS9wcm9qZWN0cy92aXRlc3QtZGV2LXZpdGVzdC1kcTZ6emUvZm9vLnRzIn0=
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitest/ui: latest => 0.28.5 
    vite: latest => 4.1.4 
    vitest: latest => 0.28.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Tanimodori** [comment]
One more simple example

```ts
export function foo() {
  return '//# sourceMappingURL=data:application/json;base64,';
}
```

**Comment by rxliuli** [comment]
Looks like the problem is caused by this modification, ref: <https://github.com/vitest-dev/vitest/issues/2427>
