### ISSUE TITLE
`globalSetup › teardown` runs twice since 0.30.0

### ISSUE THREAD

**Issue by danieldiekmeier** [vitest-dev/vitest#3181]
### Describe the bug

In Vitest 0.30.0, the global `teardown` runs twice. I configured it like this:

```js
// vite.config.js

export default defineConfig({
  test: {
    globalSetup: ['./setup.ts']
  }
})
```

```js
// setup.ts

export function teardown() {
  console.log('teardown!');
}
```

In Vitest 0.29, the `teardown` only ran once. This was much better, because I close a Postgres connection pool in there, which actually throws an error if it gets closed twice.

I think/hope this is a bug. I hope Vitest can return to the previous behaviour!

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-searqk?file=setup.ts

1. Run `npm run test:run` (should run automatically when opening the link)
2. `teardown!` is printed twice

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 30.25 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.asdf/installs/nodejs/18.15.0/bin/node
    npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 112.0.5615.49
    Edge: 112.0.1722.39
    Firefox: 103.0.2
    Firefox Developer Edition: 111.0
    Safari: 16.4
    Safari Technology Preview: 16.4
  npmPackages:
    @vitest/coverage-c8: ^0.29.8 => 0.29.8
    vite: ^4.2.1 => 4.2.1
    vitest: ^0.29.8 => 0.29.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by neo-ctataryn** [comment]
This is happening to me as well with `v0.30.1`. I did a `console.log(new Error())` at the top of my `teardown()` file and here's what the stack looks like:

```
Error
    at Object.teardown (/home/craiger/src/myproject/test/unit/lib/vitest/global-setup.ts:38:15)
    at Context.buildEnd (file:///home/craiger/src/myproject/node_modules/vitest/dist/vendor-cli-api.70680cd5.js:12127:74)
    at hookParallel (file:///home/craiger/src/myproject/node_modules/vite/dist/node/chunks/dep-79892de8.js:42977:47)
    at Object.close (file:///home/craiger/src/myproject/node_modules/vite/dist/node/chunks/dep-79892de8.js:43422:19)
    at Object.close (file:///home/craiger/src/myproject/node_modules/vite/dist/node/chunks/dep-79892de8.js:62841:27)
    at Vitest.close (file:///home/craiger/src/myproject/node_modules/vitest/dist/vendor-cli-api.70680cd5.js:14121:21)
    at startVitest (file:///home/craiger/src/myproject/node_modules/vitest/dist/vendor-cli-api.70680cd5.js:20793:13)
    at async start (file:///home/craiger/src/myproject/node_modules/vitest/dist/cli.js:106:17)
    at async CAC.run (file:///home/craiger/src/myproject/node_modules/vitest/dist/cli.js:79:3)
```
AND
```
Error
    at Object.teardown (/home/craiger/src/myproject/test/unit/lib/vitest/global-setup.ts:38:15)
    at Context.buildEnd (file:///home/craiger/src/myproject/node_modules/vitest/dist/vendor-cli-api.70680cd5.js:12127:74)
    at hookParallel (file:///home/craiger/src/myproject/node_modules/vite/dist/node/chunks/dep-79892de8.js:42977:47)
    at Object.close (file:///home/craiger/src/myproject/node_modules/vite/dist/node/chunks/dep-79892de8.js:43422:19)
    at Object.close (file:///home/craiger/src/myproject/node_modules/vite/dist/node/chunks/dep-79892de8.js:62841:27)
    at WorkspaceProject.close (file:///home/craiger/src/myproject/node_modules/vitest/dist/vendor-cli-api.70680cd5.js:13596:21)
    at file:///home/craiger/src/myproject/node_modules/vitest/dist/vendor-cli-api.70680cd5.js:14122:39
    at Array.map (<anonymous>)
    at Vitest.close (file:///home/craiger/src/myproject/node_modules/vitest/dist/vendor-cli-api.70680cd5.js:14122:26)
    at startVitest (file:///home/craiger/src/myproject/node_modules/vitest/dist/vendor-cli-api.70680cd5.js:20793:13)
    at async start (file:///home/craiger/src/myproject/node_modules/vitest/dist/cli.js:106:17)
    at async CAC.run (file:///home/craiger/src/myproject/node_modules/vitest/dist/cli.js:79:3)
vitest teardown() called
```

So it looks like one of the `teardown()`s is being initiated from `WorkspaceProject.close`, whereas if I downgrade to `v0.29.8` that `WorkspaceProject.close` invocation never happens and `teardown()` is only invoked once.

Hope this extra info helps.

**Comment by sheremet-va** [comment]
> Hope this extra info helps.

Thank you for your investigation. #3188 should fix this
