### ISSUE TITLE
vite-node stops working properly with `minimatch` since 0.31.2

### ISSUE THREAD

**Issue by jameschenjav** [vitest-dev/vitest#3609]
### Describe the bug

It was working with `vite-node ./my/script.ts`, now it shows

```
> vite-node my/script

xxx/node_modules/.pnpm/minimatch@9.0.1/node_modules/minimatch/dist/mjs/index.js:126
        AST: class __vite_ssr_import_2__.AST extends orig.AST {
                                        ^

SyntaxError: Unexpected token '.'
    at new Script (node:vm:100:7)
    at createScript (node:vm:259:10)
    at Object.runInThisContext (node:vm:307:10)
    at ViteNodeRunner.directRequest (file://xxx/node_modules/.pnpm/vite-node@0.31.2_@types+node@18.16.18/node_modules/vite-node/dist/client.mjs:321:19)
    at ViteNodeRunner.cachedRequest (file://xxx/node_modules/.pnpm/vite-node@0.31.2_@types+node@18.16.18/node_modules/vite-node/dist/client.mjs:184:14)
    at ViteNodeRunner.dependencyRequest (file://xxx/node_modules/.pnpm/vite-node@0.31.2_@types+node@18.16.18/node_modules/vite-node/dist/client.mjs:219:12)
    at xxx/node_modules/.pnpm/glob@10.2.7/node_modules/glob/dist/mjs/index.js:1:31
    at ViteNodeRunner.directRequest (file://xxx/node_modules/.pnpm/vite-node@0.31.2_@types+node@18.16.18/node_modules/vite-node/dist/client.mjs:326:5)
    at ViteNodeRunner.cachedRequest (file://xxx/node_modules/.pnpm/vite-node@0.31.2_@types+node@18.16.18/node_modules/vite-node/dist/client.mjs:184:14)
    at ViteNodeRunner.dependencyRequest (file://xxx/node_modules/.pnpm/vite-node@0.31.2_@types+node@18.16.18/node_modules/vite-node/dist/client.mjs:219:12)

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-kffe8s

In this example, run `npm run rep` will replicate the issue. As a counter example, `npm run rep-tsx` will execute without a problem.

Simply run with `rimraf('*.tmp', { glob: true })` it will raise the exception.

### System Info

```shell
> pnpx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers
  System:
    OS: Linux 6.3 Fedora Linux 37 (Workstation Edition)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 14.60 GB / 30.54 GB
    Container: Yes
    Shell: 3.6.1 - /usr/bin/fish
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 1.22.19 - ~/.local/share/pnpm/yarn
    npm: 9.6.7 - ~/.volta/tools/image/npm/9.6.7/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 114.0
  npmPackages:
    vite: ^4.3.9 => 4.3.9

> pnpm -v
8.6.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jameschenjav** [comment]
This issue can be closed now. Last week I updated vite to 4.4.2+, everything started working fine.
