### ISSUE TITLE
[vite-node] Global variable collision when 2 packages define the same variable

### ISSUE THREAD

**Issue by m-sallam** [vitest-dev/vitest#3782]
### Describe the bug

when using the following packages 
- `@aws-sdk/client-sqs`
- `p-queue`

i believe a variable collision happens when accessing the `__classPrivateFieldGet` variable

running `npm run dev` in the reproduction repo should result in the following error
```
/Users/user/code/vite-node-global-collision/node_modules/@aws-crypto/crc32/node_modules/tslib/tslib.js:250
        return privateMap.get(receiver);
                          ^

TypeError: privateMap.get is not a function
    at __classPrivateFieldGet (/Users/user/code/vite-node-global-collision/node_modules/@aws-crypto/crc32/node_modules/tslib/tslib.js:250:27)
    at PQueue.set concurrency [as concurrency] (/Users/user/code/vite-node-global-collision/node_modules/p-queue/dist/index.js:91:9)
    at new PQueue (/Users/user/code/vite-node-global-collision/node_modules/p-queue/dist/index.js:78:26)
    at /Users/user/code/vite-node-global-collision/index.js:4:15
    at ViteNodeRunner.directRequest (file:///Users/user/code/vite-node-global-collision/node_modules/vite-node/dist/client.mjs:341:5)
    at ViteNodeRunner.cachedRequest (file:///Users/user/code/vite-node-global-collision/node_modules/vite-node/dist/client.mjs:197:14)
    at ViteNodeRunner.executeFile (file:///Users/user/code/vite-node-global-collision/node_modules/vite-node/dist/client.mjs:169:12)
    at CAC.run (file:///Users/user/code/vite-node-global-collision/node_modules/vite-node/dist/cli.mjs:70:5)
```

p-queue is using `__classPrivateFieldGet` from the `@aws-sdk/client-sqs`'s dependencies instead of its own.

while running `npm run start` start the app normally.

`__classPrivateFieldGet` is defined at
- `node_modules/@aws-crypto/crc32/node_modules/tslib/tslib.js` for the `@aws-sdk/client-sqs` package
- `node_modules/p-queue/dist/index.js` for the `p-queue` package

### Reproduction

https://github.com/m-sallam/vite-node-global-collision

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 67.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.5.2
  npmPackages:
    vite: ^4.4.4 => 4.4.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This should be fixed with Vite 5 or higher.
