### ISSUE TITLE
Error on loading the test suite on Windows partitioned HDD or subst created drive

### ISSUE THREAD

**Issue by riovir** [vitest-dev/vitest#3812]
### Describe the bug

Unable to run Vitest using TypeScript from a partitioned drive on Windows 10. (If the tests are ts files)

Stack trace caused by `getCurrentSuite()` being undefined:
```
TypeError: Cannot read properties of undefined (reading 'test')
    at Object.<anonymous> (file:///E:/workspaces/vitest-on-windows-virtual-drive/node_modules/@vitest/runner/dist/index.js:176:22)
    at Module.chain2 (file:///E:/workspaces/vitest-on-windows-virtual-drive/node_modules/@vitest/runner/dist/utils.js:99:17)
    at Z:\vitest-on-windows-virtual-drive\test.spec.ts:3:1
    at VitestExecutor.directRequest (file:///Z:/vitest-on-windows-virtual-drive/node_modules/vite-node/dist/client.mjs:341:5)
    at VitestExecutor.cachedRequest (file:///Z:/vitest-on-windows-virtual-drive/node_modules/vite-node/dist/client.mjs:197:14)
    at VitestExecutor.executeId (file:///Z:/vitest-on-windows-virtual-drive/node_modules/vite-node/dist/client.mjs:173:12)
    at DebugRunner.importFile (Z:\vitest-on-windows-virtual-drive\debug-runner.ts:7:20)
    at collectTests (file:///Z:/vitest-on-windows-virtual-drive/node_modules/@vitest/runner/dist/index.js:447:7)
    at startTests (file:///Z:/vitest-on-windows-virtual-drive/node_modules/@vitest/runner/dist/index.js:765:17)
    at file:///Z:/vitest-on-windows-virtual-drive/node_modules/vitest/dist/entry.js:278:7
```
_Notice the mix of drives E: (real HDD) and Z: (partition / subst-created)._

### Reproduction

On Windows 10 Pro and Enterprise version 22H2 (build: 19045.3208)
Have the repo of https://github.com/riovir/vitest-on-windows-virtual-drive cloned to
  - a partitioned drive
  - or create one with `subst Z: E:\[location_of_the_repo]`

After `npm ci`,  `npm test` or `npm run debug` (for more context).

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900KF
    Memory: 14.22 GB / 31.82 GB
  Binaries:
    Node: 20.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by riovir** [comment]
In the reprod, note that, when tested on a partitioned drive, it was green on the first run. Then setting the `debug.config.ts` to have `globals: true` caused `npm run debug` to fail. But then after the tests started failing even with `npm test` which doesn't do anything with the config.

**Comment by riovir** [comment]
On a partitioned drive the follow stack trace is produced by the `npm run debug`:

```
TypeError: Cannot read properties of undefined (reading 'test')
    at Object.<anonymous> (file:///D:/Projects/design-system/test/vitest-on-windows-virtual-drive/node_modules/@vitest/runner/dist/index.js:176:22)
    at Module.chain2 (file:///D:/Projects/design-system/test/vitest-on-windows-virtual-drive/node_modules/@vitest/runner/dist/utils.js:99:17)
    at d:\Projects\design-system\test\vitest-on-windows-virtual-drive\test.spec.ts:3:1
    at VitestExecutor.directRequest (file:///d:/Projects/design-system/test/vitest-on-windows-virtual-drive/node_modules/vite-node/dist/client.mjs:341:5)
    at VitestExecutor.cachedRequest (file:///d:/Projects/design-system/test/vitest-on-windows-virtual-drive/node_modules/vite-node/dist/client.mjs:197:14)
    at VitestExecutor.executeId (file:///d:/Projects/design-system/test/vitest-on-windows-virtual-drive/node_modules/vite-node/dist/client.mjs:173:12)
    at DebugRunner.importFile (d:\Projects\design-system\test\vitest-on-windows-virtual-drive\debug-runner.ts:7:20)
    at collectTests (file:///d:/Projects/design-system/test/vitest-on-windows-virtual-drive/node_modules/@vitest/runner/dist/index.js:447:7)
    at startTests (file:///d:/Projects/design-system/test/vitest-on-windows-virtual-drive/node_modules/@vitest/runner/dist/index.js:765:17)
    at file:///d:/Projects/design-system/test/vitest-on-windows-virtual-drive/node_modules/vitest/dist/entry.js:278:7
```

Notice the drive letter casing of D: and d:

**Comment by sheremet-va** [comment]
Can you add a guide how to create a petitioned drive to reproduce this?

**Comment by riovir** [comment]
Turns out that it wasn't the partitioning after all. The real culprit seems to be a drive letter mismatch. Either in the casing, if the terminal's starting path has it lower-cased _(workaround: don't do that, make sure the path has an upper-case drive letter)_, or the `subst` command.

To be clear the real issue in my case was the lower-case drive letter. We stumbled onto the `subst` command merely because we tried to reproduce the issue in a simpler way, believing that it was a partition issue.

**Comment by sheremet-va** [comment]
Then it's a duplicate of #3776

**Comment by callmeberzerker** [comment]
I am still experiencing this very issue on the latest vitest@0.34.6 (tried the latest betas as well). Any solution?

**Comment by sheremet-va** [comment]
> I am still experiencing this very issue on the latest vitest@0.34.6 (tried the latest betas as well). Any solution?

Please, provide a reproduction. The bug mentioned in the issue was fixed with 0.34.0.
