### ISSUE TITLE
Auto install fails for `@vitest/coverage-v8` when using bun

### ISSUE THREAD

**Issue by ImLunaHey** [vitest-dev/vitest#3893]
### Describe the bug

I added `vitest` as a script called `test`, then ran `bun run test --coverage`. Since I didn't have the coverage package install I was prompted to install it. Bun then crashes.

Happy to open this under bun's issue tracker if it's more of a issue on their end.

```
Failed to parse argument due to unexpected single dash

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Command failed with exit code 1: bun install -D @vitest/coverage-v8
    at makeError$1 (file:///Users/xo/code/ImLunaHey/vote/node_modules/vitest/dist/chunk-install-pkg.dd40cbef.js:978:11)
    at handlePromise (file:///Users/xo/code/ImLunaHey/vote/node_modules/vitest/dist/chunk-install-pkg.dd40cbef.js:1514:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ensurePackageInstalled (file:///Users/xo/code/ImLunaHey/vote/node_modules/vitest/dist/vendor-node.caa511fc.js:83:5)
    at async startVitest (file:///Users/xo/code/ImLunaHey/vote/node_modules/vitest/dist/vendor-node.caa511fc.js:20493:12)
    at async start (file:///Users/xo/code/ImLunaHey/vote/node_modules/vitest/dist/cli.js:131:17) {
  shortMessage: 'Command failed with exit code 1: bun install -D @vitest/coverage-v8',
  command: 'bun install -D @vitest/coverage-v8',
  escapedCommand: 'bun install -D "@vitest/coverage-v8"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}



error: script "test" exited with code 1 (SIGHUP)
```

### Reproduction

N/A

### System Info

```shell
System:
    OS: macOS 12.6.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 364.80 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.3.0 - ~/.nvm/versions/node/v18.3.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.3.0/bin/npm
    pnpm: 8.5.1 - ~/.nvm/versions/node/v18.3.0/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5
    Safari Technology Preview: 16.4
  npmPackages:
    vitest: ^0.34.1 => 0.34.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
If the command failed, then the command failed. Looks like it cannot install `@vitest/coverage-v8` for some reason. I would recommend opening an issue in their repo.
