### ISSUE TITLE
Diff's including a undefined expected/received value causes a crash 

### ISSUE THREAD

**Issue by ElmoArmy** [vitest-dev/vitest#411]
### Describe the bug

A change in ^0.0.127 introduced a regression when diff'ing a test failure that contains an undefined token.

Given a test such as : 
 ```typescript
 test('expecting an undefined result', () => {
  expect(undefined).toBe(2);
});
```

^0.0.127 Results in:
```console
 ❯ eval test/basic.test.ts:24:20
     22| 
     23| test('expecting an undefined result', () => {
     24|   expect(undefined).toBe(2);
       |                    ^
     25| });
     26| 
 UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'split')
    at Diff.lineDiff.tokenize (file:///home/projects/node-woskth/node_modules/vitest/dist/diff-711cddf1.js:340:32)
    at Diff.diff (file:///home/projects/node-woskth/node_modules/vitest/dist/diff-711cddf1.js:62:39)
    at diffLines (file:///home/projects/node-woskth/node_modules/vitest/dist/diff-711cddf1.js:365:19)
    at structuredPatch (file:///home/projects/node-woskth/node_modules/vitest/dist/diff-711cddf1.js:537:14)
    at createTwoFilesPatch (file:///home/projects/node-woskth/node_modules/vitest/dist/diff-711cddf1.js:685:22)
    at createPatch (file:///home/projects/node-woskth/node_modules/vitest/dist/diff-711cddf1.js:688:10)
    at unifiedDiff (file:///home/projects/node-woskth/node_modules/vitest/dist/diff-711cddf1.js:4746:15)
    at displayDiff (file:///home/projects/node-woskth/node_modules/vitest/dist/diff-711cddf1.js:4656:43)
    at Module.printError (file:///home/projects/node-woskth/node_modules/vitest/dist/diff-711cddf1.js:4625:5)
    at async DefaultReporter.printTaskErrors (file:///home/projects/node-woskth/node_modules/vitest/dist/index-05648ba5.js:7118:7)
```

Expected (results from ^0.0.126 ): 
```console
 FAIL  test/basic.test.ts > expecting an undefined result
AssertionError: expected undefined to equal 2
 ❯ Proxy.methodWrapper node_modules/chai/lib/chai/utils/addMethod.js:57:25
 ❯ eval test/basic.test.ts:24:20
     22| 
     23| test('expecting an undefined result', () => {
     24|   expect(undefined).toBe(2);
       |                    ^
     25| });
     26| 

  - Expected   2
  + Received   undefined
```

### Reproduction

[Stackblitz : Reproducing bug in  ^0.0.127 ](https://stackblitz.com/edit/node-woskth?devtoolsheight=33&file=test/basic.test.ts)
[Stackblitz : Working as expected in  ^0.0.126 ](https://stackblitz.com/edit/node-tvf3g8?devtoolsheight=33&file=test/basic.test.ts)

### System Info

```shell
System:
    OS: Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: Unknown - /bin/jsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    vite: ^2.7.10 => 2.7.10 
    vitest: ^0.0.127 => 0.0.127
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 11joselu** [comment]
Maybe we need to revert https://github.com/vitest-dev/vitest/pull/407. But we can investigate why AssertionError does not have `actual` attribute in that assertion
