### ISSUE TITLE
Vitest bypasses vite plugins causing errors

### ISSUE THREAD

**Issue by maasha** [vitest-dev/vitest#4817]
### Describe the bug

I have a project that is dependent on some AMD modules that vite can only handle using babel and commonjs plugins. While that works fine for vite, it breaks in vitest. The error indicates vitest operates on the AMD module before conversion:

```
test/basic.test.ts
ReferenceError: define is not defined
 - /node_modules/azure-devops-extension-api/index.js:1:76
 - /blitz.a2aabdd9.js:352:197209
 - /blitz.a2aabdd9.js:352:376062
 - /blitz.a2aabdd9.js:352:375135
```

`vite.config.ts`:

```
/// <reference types="vitest" />

// Configure Vitest (https://vitest.dev/config/)

import { defineConfig } from 'vite'
import babel from "vite-plugin-babel";
import commonjs from 'vite-plugin-commonjs'

export default defineConfig({
  plugins: [
    babel({
        babelConfig: {
            plugins: ['transform-amd-to-commonjs'],
        },
    }),
    commonjs(),
],
  test: {
    /* for example, use global to avoid globals imports (describe, test, expect): */
    // globals: true,
  },
})
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-lsfx2b?file=package.json,src%2Fbasic.ts,vite.config.ts&initialPath=__vitest__/

npm install -s azure-devops-extension-api vite-plugin-babel babel-plugin-transform-amd-to-commonjs vite-plugin-commonjs

And add

```
import { getClient } from 'azure-devops-extension-api'
```

to `basic.ts`

### System Info

```shell
System:
    OS: macOS 11.7.8
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 191.62 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.5.1 - /usr/local/bin/node
    npm: 9.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 16.4.1
  npmPackages:
    @vitejs/plugin-react: ^4.0.1 => 4.0.4
    @vitest/coverage-istanbul: ^0.32.2 => 0.32.4
    vite: ^4.3.9 => 4.4.9
    vitest: ^0.34.6 => 0.34.6



I have also tried with "vite": "^4.5.1", "vitest": "^1.0.4"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
By default, Vitest doesn't crawl your dependencies to pre-bundle them like Vite does. You can add both `azure-devops-extension-sdk`, `azure-devops-extension-api` to `deps.optimizer.web.include`, but currently Vitest also doesn't process those dependencies afterwards so `commonjs` plugin will not be applied which makes this useless in your case. However, it is possible to configure Vitest to process those files with both plugins by inlined them and specifying plugin options like so:

```ts

import { defineConfig } from 'vite'
import babel from "vite-plugin-babel";
import commonjs from 'vite-plugin-commonjs'

export default defineConfig({
  plugins: [
    babel({
      filter: /.*/,
      include: [/azure-devops-extension-api/],
      babelConfig: {
        plugins: ['transform-amd-to-commonjs'],
      },
    }),
    commonjs({
      filter: (id) => id.includes('azure-devops-extension-api') || id.includes('azure-devops-extension-sdk'),
    }),
],
  test: {
    environment: 'jsdom',
    server: {
      deps: {
        inline: ['azure-devops-extension-sdk', 'azure-devops-extension-api'],
      }
    }
  },
})
```

It might be wise to create a separate Vitest file to handle such use case.

**Comment by maasha** [comment]
I tried this on my projet, but I still can only get vite to work with the AMD modules while vitest still errors with the AMD typical error `ReferenceError: define is not defined`.

My `vite.config.ts`:

```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from 'tailwindcss'
import babel from 'vite-plugin-babel'
import commonjs from 'vite-plugin-commonjs'

export default defineConfig({
    base: '/',
    plugins: [
        react(),
        babel({
            filter: /.*/,
            include: [/azure-devops-extension-api/, /azure-devops-extension-sdk/],
            babelConfig: {
                plugins: ['transform-amd-to-commonjs'],
            },
        }),
        commonjs({
            filter: (id) =>
                id.includes('azure-devops-extension-api') ||
                id.includes('azure-devops-extension-sdk'),
        }),
    ],
    server: {
        port: 8000,
    },
    css: {
        postcss: {
            plugins: [tailwindcss],
        },
    },
    build: {
        rollupOptions: {
            output: {
                assetFileNames: 'output.css',
            },
        },
    },
    define: {
        'process.env': {},
    },
})

```

And `vitest.config.ts`:

```
import { defineConfig } from 'vitest/config'

export default defineConfig({
    test: {
        reporters: ['default', 'junit'],
        coverage: {
            reporter: ['text', 'json', 'html', 'cobertura'],
            provider: 'istanbul',
        },
        environment: 'jsdom',
        globals: true,
        setupFiles: ['./src/common/test/test-setup.ts', 'dotenv/config'],
        exclude: ['**/node_modules/**', '**/temp/**'],
        server: {
            deps: {
                inline: ['azure-devops-extension-sdk', 'azure-devops-extension-api'],
            },
        },
    },
})
```

**Comment by sheremet-va** [comment]
> And `vitest.config.ts`:

Vitest config [overrides Vite config](https://vitest.dev/config/#configuration), and you didn't specify any plugin there, so it makes sense that they are not applied.

**Comment by maasha** [comment]
Ah, thanks. It is working now! Many thanks!

**Comment by maasha** [comment]
Actually, it was not completely working, but almost. With this config build worked and vitest failed:

```
...
    plugins: [
        react(),
        babel({
            babelConfig: {
                plugins: ['transform-amd-to-commonjs'],
            },
        }),
        commonjs(),
    ],
...
```

With this config vitest works, but build fails:

```
...
plugins: [
        react(),
        babel({
            filter: /.*/,
            include: [/azure-devops-extension-api/, /azure-devops-extension-sdk/],
            babelConfig: {
                plugins: ['transform-amd-to-commonjs'],
            },
        }),
        commonjs({
            filter: (id) =>
                id.includes('azure-devops-extension-api') ||
                id.includes('azure-devops-extension-sdk'),
        }),
],
test: {
      ...
      server: {
            deps: {
                inline: ['azure-devops-extension-api', 'azure-devops-extension-sdk'],
            },
        },
}
...

```





```
vite v4.5.1 building for test...
node_modules/azure-devops-extension-api/Common/Fetch.js (119:25) "default" is not exported by "node_modules/whatwg-fetch/fetch.js", imported by "node_modules/azure-devops-extension-api/Common/Fetch.js".
✓ 2794 modules transformed.
✓ built in 7.00s
"getClient" is not exported by "node_modules/azure-devops-extension-api/index.js", imported by "src/utils/azure-save-deviation.util.ts".
file: /Users/maasha/install/src/PharmaIT/TestManagement/src/utils/azure-save-deviation.util.ts:7:9
5: } from 'azure-devops-extension-api/WorkItemTracking'
6: import * as SDK from 'azure-devops-extension-sdk'
7: import { getClient } from 'azure-devops-extension-api'
            ^
8: import { ITestCase } from '../common/interfaces/work-items/test-case.interface'
9: import { ITestResult } from '../common/interfaces/work-items/test-result.interface'
error during build:
RollupError: "getClient" is not exported by "node_modules/azure-devops-extension-api/index.js", imported by "src/utils/azure-save-deviation.util.ts".
    at error (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at Module.error (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:13604:16)
    at Module.traceVariable (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:14029:29)
    at ModuleScope.findVariable (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:12547:39)
    at FunctionScope.findVariable (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at ChildScope.findVariable (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:7082:38)
    at Identifier.bind (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:8267:40)
    at CallExpression.bind (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:5846:28)
    at CallExpression.bind (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:9833:15)
    at ExpressionStatement.bind (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:5850:23)
    at BlockStatement.bind (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:5846:28)
    at FunctionDeclaration.bind (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:5850:23)
    at ExportNamedDeclaration.bind (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:10616:27)
    at Program.bind (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:5846:28)
    at Module.bindReferences (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:13600:18)
    at Graph.sortModules (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:25665:20)
    at Graph.build (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:25549:14)
    at async file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:26510:13
    at async catchUnfinishedHookActions (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:25722:16)
    at async rollupInternal (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/rollup/dist/es/shared/node-entry.js:26505:5)
    at async build (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/vite/dist/node/chunks/dep-68d1a114.js:48079:18)
    at async CAC.<anonymous> (file:///Users/maasha/install/src/PharmaIT/TestManagement/node_modules/vite/dist/node/cli.js:842:9)
```

**Comment by sheremet-va** [comment]
This is why you need to have a separate `vitest.config` that doesn't influence your vite build.
