### ISSUE TITLE
The CLI options --poolOptions, --minWorkers, and --maxWorkers seem unusable

### ISSUE THREAD

**Issue by jgosmann** [vitest-dev/vitest#4922]
### Describe the bug

It is not clear how the CLI options
* `--poolOptions`,
* `--minWorkers`,
* and `--maxWorkers`
are supposed to be used. The [documentation](https://vitest.dev/guide/cli) does not provide any examples. Everything I tried gave me an error (see reproduction below). 

### Reproduction

# --poolOptions

```
❯ npx vitest --poolOptions threads.maxThreads=4                                                                 258fad3

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Cannot create property 'threads' on string 'threads.maxThreads=4'
    at config (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/vendor/node.wTZytysZ.js:8511:62)
    at runConfigHook (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:68054:31)
    at async resolveConfig (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:67504:14)
    at async _createServer (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:59972:20)
    at async createViteServer (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/vendor/node.wTZytysZ.js:7472:18)
    at async createVitest (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/vendor/node.wTZytysZ.js:8632:18)
    at async startVitest (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/vendor/node.wTZytysZ.js:15057:15)
    at async start (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/cli.js:143:17)
```

Maybe it needs to be a JSON object? Nope, same error:

```
❯ npx vitest --poolOptions '{"threads":{"maxThreads":4}}'                                                       375498b

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Cannot create property 'threads' on string '{"threads":{"maxThreads":4}}'
    at config (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/vendor/node.wTZytysZ.js:8511:62)
    at runConfigHook (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:68054:31)
    at async resolveConfig (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:67504:14)
    at async _createServer (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:59972:20)
    at async createViteServer (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/vendor/node.wTZytysZ.js:7472:18)
    at async createVitest (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/vendor/node.wTZytysZ.js:8632:18)
    at async startVitest (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/vendor/node.wTZytysZ.js:15057:15)
    at async start (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/cli.js:143:17)
```

# --minWorkers/--maxWorkers

```
❯ npx vitest --minWorkers 1 --maxWorkers 4                                                                    375498b

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: input.includes is not a function
    at normalizeWindowsPath (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/pathe/dist/shared/pathe.92c04245.mjs:2:24)
    at normalize (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/pathe/dist/shared/pathe.92c04245.mjs:17:10)
    at Array.map (<anonymous>)
    at start (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/cli.js:143:52)
    at CAC.<anonymous> (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/cli.js:70:58)
    at CAC.runMatchedCommand (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/cac/dist/index.mjs:610:34)
    at CAC.parse (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/cac/dist/index.mjs:537:12)
    at file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/cli.js:72:7
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
```

```
❯ npx vitest --minWorkers=1 --maxWorkers=4                                                                    375498b

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: input.includes is not a function
    at normalizeWindowsPath (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/pathe/dist/shared/pathe.92c04245.mjs:2:24)
    at normalize (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/pathe/dist/shared/pathe.92c04245.mjs:17:10)
    at Array.map (<anonymous>)
    at start (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/cli.js:143:52)
    at CAC.<anonymous> (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/cli.js:70:58)
    at CAC.runMatchedCommand (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/cac/dist/index.mjs:610:34)
    at CAC.parse (file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/cac/dist/index.mjs:537:12)
    at file:///Users/gosmannj/Documents/titan/titan/ui/webapp/node_modules/vitest/dist/cli.js:72:7
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
```

`npx vitest --minWorkers --maxWorkers` actually works but seems to use a single worker. How do I set a different number?

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 24.06 GB / 64.00 GB
    Shell: 5.9 - /opt/local/bin/zsh
  Binaries:
    Node: 20.10.0 - /opt/local/bin/node
    npm: 10.2.5 - /opt/local/bin/npm
  Browsers:
    Chrome: 120.0.6099.199
    Edge: 120.0.2210.121
    Safari: 17.2.1
  npmPackages:
    @vitejs/plugin-legacy: ^5.2.0 => 5.2.0
    @vitejs/plugin-react: ^4.2.1 => 4.2.1
    @vitest/ui: ^1.1.3 => 1.1.3
    vite: ^5.0.10 => 5.0.10
    vitest: ^1.0.4 => 1.1.3
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`--minWorkers/--maxWorkers` is a bug. Pool options are added using dot notation:

```
npx vitest --poolOptions.threads.maxThreads=4
```

You can see an example with `poolOptions.threads.isolate` on the same page you linked
