### ISSUE TITLE
RuntimeError: unreachable

### ISSUE THREAD

**Issue by solidsnakedev** [vitest-dev/vitest#4923]
### Describe the bug

I'm switching from vitest 0.34.6 to 1.1.3, but whenerver I run npx vitest run I get this error
```
RuntimeError: unreachable
      at null.<anonymous> (wasm://wasm/00a9f9f2:1:1949402)
      at null.<anonymous> (wasm://wasm/00a9f9f2:1:2470603)
      at null.<anonymous> (wasm://wasm/00a9f9f2:1:2508210)
      at null.<anonymous> (wasm://wasm/00a9f9f2:1:2427567)
      at null.<anonymous> (wasm://wasm/00a9f9f2:1:1825441)
      at TransactionBuilder.add_inputs_from (/Users/jonathan/Documents/projects/contracts/anastasia-labs/linear-vesting-offchain/node_modules/.pnpm/@anastasia-labs+lucid-cardano-fork@0.10.7/node_modules/@anastasia-labs/lucid-cardano-fork/esm/src/core/libs/cardano_multiplatform_lib/nodejs/cardano_multiplatform_lib.generated.js:21738:12)
      at Tx.complete (/Users/jonathan/Documents/projects/contracts/anastasia-labs/linear-vesting-offchain/node_modules/.pnpm/@anastasia-labs+lucid-cardano-fork@0.10.7/node_modules/@anastasia-labs/lucid-cardano-fork/esm/src/lucid/tx.js:337:28)
      at Module.collectVestingTokens (/Users/jonathan/Documents/projects/contracts/anastasia-labs/linear-vesting-offchain/src/endpoints/collectVestingTokens.ts:100:18)
      at /Users/jonathan/Documents/projects/contracts/anastasia-labs/linear-vesting-offchain/test/lock-unlock.test.ts:114:35
      at runTest (file:///Users/jonathan/Documents/projects/contracts/anastasia-labs/linear-vesting-offchain/node_modules/.pnpm/@vitest+runner@1.1.3/node_modules/@vitest/runner/dist/index.js:675:11)
```

### Reproduction

Use a library using wasm module, switch from 0.34.6 to 1.1.3
https://github.com/Anastasia-Labs/linear-vesting-offchain/tree/runtime-error

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) x64 Apple M1
    Memory: 33.10 MB / 8.00 GB
    Shell: 3.6.1 - /Users/jonathan/.nix-profile/bin/fish
  Binaries:
    Node: 20.0.0 - /nix/store/2nv4lnxn3sgrfq934ms4dp5f2i0bfqxg-nodejs-20.0.0/bin/node
    npm: 9.6.4 - /nix/store/2nv4lnxn3sgrfq934ms4dp5f2i0bfqxg-nodejs-20.0.0/bin/npm
    pnpm: 8.4.0 - /nix/store/ajw6jhbyjaj6nl4jqf9rwrrvd9wg99vy-pnpm-8.4.0/bin/pnpm
  Browsers:
    Brave Browser: 120.1.61.114
    Chrome: 120.0.6099.199
    Safari: 17.0
  npmPackages:
    vite: ^5.0.11 => 5.0.11 
    vitest: 1.1.3 => 1.1.3 
```
```


### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by solidsnakedev** [comment]
https://github.com/Anastasia-Labs/linear-vesting-offchain/tree/runtime-error

**Comment by grod220** [comment]
Any luck finding a solution? We area also getting the same wasm-pack error. Also, that repo appears to be private.

**Comment by rygine** [comment]
i created a repository that reproduces the error. please take a look.

https://github.com/rygine/vitest-wasm-unreachable

**Comment by AriPerkkio** [comment]
> https://github.com/rygine/vitest-wasm-unreachable

Does it happen all the time or just randomly? I'm unable to reproduce the issue on Github Codespaces with this one. Tests run successfully all the time.

**Comment by AriPerkkio** [comment]
@rygine that reproduction crashes even without Vitest. Remove `describe` and `test` and run it directly with Node:

![image](https://github.com/vitest-dev/vitest/assets/14806298/182a2503-22f7-448b-befa-e39fc8183504)

**Comment by rygine** [comment]
thanks for pointing that out! i'm currently using jest for testing, which is using the CommonJS export for the WASM module. that seems to be working just fine when i remove `type: "module"` from the example repo.

i'll investigate the cause of the ESM export issue.
