### ISSUE TITLE
[Bug report]: Cannot find module @rollup/rollup-darwin-arm64

### ISSUE THREAD

**Issue by GodAraden** [vitest-dev/vitest#5049]
### Describe the bug

I followed the steps in the [guide](https://vitest.dev/guide/#writing-tests), when i run 'pnpm test', it throw an error:

```
/Users/godaraden/Desktop/demo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js:87
                throw new Error(
                      ^

Error: Cannot find module @rollup/rollup-darwin-arm64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/godaraden/Desktop/demo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js:87:9)
    at Object.<anonymous> (/Users/godaraden/Desktop/demo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js:96:48)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at cjsLoader (node:internal/modules/esm/translators:359:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:308:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-arm64'
  Require stack:
  - /Users/godaraden/Desktop/demo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
      at Module._load (node:internal/modules/cjs/loader:990:27)
      at Module.require (node:internal/modules/cjs/loader:1237:19)
      at require (node:internal/modules/helpers:176:18)
      at requireWithFriendlyError (/Users/godaraden/Desktop/demo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js:69:10)
      at Object.<anonymous> (/Users/godaraden/Desktop/demo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js:96:48)
      at Module._compile (node:internal/modules/cjs/loader:1378:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
      at Module.load (node:internal/modules/cjs/loader:1212:32)
      at Module._load (node:internal/modules/cjs/loader:1028:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/godaraden/Desktop/demo/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/native.js'
    ]
  }
}

Node.js v21.6.1
 ELIFECYCLE  Test failed. See above for more details.
```

When I tried to install rollup@4.9.5 to my demo project, then remove `pnpm-lock.yaml` and `node_modules`, finally I run 'pnpm i' and 'pnpm test' again, it work well

I tried to re-execute the above steps under rollup@4.9.6, but it throw `Error: Cannot find module @rollup/rollup-darwin-arm64` again...

### Reproduction

https://github.com/GodAraden/vitest-bug-report-demo.git

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M2 Pro
    Memory: 408.81 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm
    pnpm: 8.14.3 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.3
  npmPackages:
    vitest: ^1.2.0 => 1.2.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by amirakbulut** [comment]
I have the same issue using `"vite": "5.0.12"`, downgrading to `4.5.1` seems to be the temporary fix for me.

**Comment by EmilyRagan** [comment]
I am also having this issue, specifically when trying to configure use vitest in npm workspaces

**Comment by xianxin011** [comment]
You add the codes to your `package.json`
```json
"optionalDependencies": {
    "@rollup/rollup-android-arm-eabi": "4.22.4",
    "@rollup/rollup-android-arm64": "4.22.4",
    "@rollup/rollup-darwin-arm64": "4.22.4",
    "@rollup/rollup-darwin-x64": "4.22.4",
    "@rollup/rollup-linux-arm-gnueabihf": "4.22.4",
    "@rollup/rollup-linux-arm-musleabihf": "4.22.4",
    "@rollup/rollup-linux-arm64-gnu": "4.22.4",
    "@rollup/rollup-linux-arm64-musl": "4.22.4",
    "@rollup/rollup-linux-powerpc64le-gnu": "4.22.4",
    "@rollup/rollup-linux-riscv64-gnu": "4.22.4",
    "@rollup/rollup-linux-s390x-gnu": "4.22.4",
    "@rollup/rollup-linux-x64-gnu": "4.22.4",
    "@rollup/rollup-linux-x64-musl": "4.22.4",
    "@rollup/rollup-win32-arm64-msvc": "4.22.4",
    "@rollup/rollup-win32-ia32-msvc": "4.22.4",
    "@rollup/rollup-win32-x64-msvc": "4.22.4",
    "fsevents": "~2.3.2"
  }
```
then  `npm install` your project

**Comment by alexilyaev** [comment]
I'm seeing this because the Vitest VS Code fails to load.

<img width="357" height="98" alt="Image" src="https://github.com/user-attachments/assets/1de26c10-7919-4b2a-acd1-deebd2e0a548" />

<details>
<summary>Extension logs</summary>

```
[INFO 9:22:00 PM] [v0.0.0] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 9:22:00 PM] [API] Resolving configs: frontend-page-prism/vitest.config.ts
[INFO 9:22:00 PM] [API] Running Vitest v3.2.4 (frontend-page-prism/vitest.config.ts) with "/Users/alex/.local/state/fnm_multishells/67527_1757872480922/bin/node /Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/worker.js"
[Error 9:22:01 PM] There were errors during config load.
[Error 9:22:01 PM] [Error Error] Vitest failed to start: 
Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/alex/www/Node/Personal/Interviews/Intuit/frontend-page-prism/node_modules/.pnpm/rollup@4.50.1/node_modules/rollup/dist/native.js:67:9)
    at Object.<anonymous> (/Users/alex/www/Node/Personal/Interviews/Intuit/frontend-page-prism/node_modules/.pnpm/rollup@4.50.1/node_modules/rollup/dist/native.js:76:76)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
Error: Vitest failed to start: 
Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/alex/www/Node/Personal/Interviews/Intuit/frontend-page-prism/node_modules/.pnpm/rollup@4.50.1/node_modules/rollup/dist/native.js:67:9)
    at Object.<anonymous> (/Users/alex/www/Node/Personal/Interviews/Intuit/frontend-page-prism/node_modules/.pnpm/rollup@4.50.1/node_modules/rollup/dist/native.js:76:76)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
	at t.a (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:12:2545)
	at t.emit (node:events:524:28)
	at rs.lh (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:1:38384)
	at rs.emit (node:events:524:28)
	at rs.dataMessage (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:1:15831)
	at rs.getData (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:1:14694)
	at rs.startLoop (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:1:11264)
	at rs._write (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:1:10548)
	at writeOrBuffer (node:internal/streams/writable:572:12)
	at _write (node:internal/streams/writable:501:10)
	at Writable.write (node:internal/streams/writable:510:10)
	at Socket.br (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:1:39362)
	at Socket.emit (node:events:524:28)
	at addChunk (node:internal/streams/readable:561:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
	at Readable.push (node:internal/streams/readable:392:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
[INFO 9:22:01 PM] [Worker] node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Cannot find module @rollup/rollup-darwin-x64. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/Users/alex/www/Node/Personal/Interviews/Intuit/frontend-page-prism/node_modules/.pnpm/rollup@4.50.1/node_modules/rollup/dist/native.js:67:9)
    at Object.<anonymous> (/Users/alex/www/Node/Personal/Interviews/Intuit/frontend-page-prism/node_modules/.pnpm/rollup@4.50.1/node_modules/rollup/dist/native.js:76:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-darwin-x64'
  Require stack:
  - /Users/alex/www/Node/Personal/Interviews/Intuit/frontend-page-prism/node_modules/.pnpm/rollup@4.50.1/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
      at Module._load (node:internal/modules/cjs/loader:985:27)
      at Module.require (node:internal/modules/cjs/loader:1235:19)
      at require (node:internal/modules/helpers:176:18)
      at requireWithFriendlyError (/Users/alex/www/Node/Personal/Interviews/Intuit/frontend-page-prism/node_modules/.pnpm/rollup@4.50.1/node_modules/rollup/dist/native.js:49:10)
      at Object.<anonymous> (/Users/alex/www/Node/Personal/Interviews/Intuit/frontend-page-prism/node_modules/.pnpm/rollup@4.50.1/node_modules/rollup/dist/native.js:76:76)
      at Module._compile (node:internal/modules/cjs/loader:1376:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
      at Module.load (node:internal/modules/cjs/loader:1207:32)
      at Module._load (node:internal/modules/cjs/loader:1023:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/alex/www/Node/Personal/Interviews/Intuit/frontend-page-prism/node_modules/.pnpm/rollup@4.50.1/node_modules/rollup/dist/native.js'
    ]
  }
}
[INFO 9:22:01 PM] [Worker] 
Node.js v20.10.0
[Error 9:22:01 PM] [Error Error] The extension could not load any config.
Error: The extension could not load any config.
	at kl (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:13:11050)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Ai._defineTestProfiles (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:24:2314)
	at async Ai.defineTestProfiles (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:24:1701)
	at async Ai.activate (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:24:7158)
	at async Uy (/Users/alex/.cursor/extensions/vitest.explorer-1.28.2-universal/dist/extension.js:24:662)
	at async Pue._activate (file:///Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:16497)
	at async Pue._waitForDepsThenActivate (file:///Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:16439)
	at async Pue._initialize (file:///Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:15801)

```
</details>

I actually had a working setup, and after deleting `node_modules` (without making any changes) and running `pnpm install` again, it now fails to load.
While running vitest in the terminal works ok.

I'm on macOS M1

EDIT:
Restarting the OS and deleting `node_modules` and running `pnpm install` again worked 🤦🏻‍♂️
I guess there was some caching issue.

**Comment by hi-ogawa** [comment]
This is often rollup and package manager issue, so it's not actionable for Vitest. It might have been a temporary issue, so please test again with the latest version. Closing as OP's reproduction is not accessible.
