### ISSUE TITLE
`--clearScreen` not accepted as CLI argument

### ISSUE THREAD

**Issue by paularmstrong** [vitest-dev/vitest#5185]
### Describe the bug

Expected Vite's `--clearScreen=false` argument to be accepted by Vitest (not just in the config)

### Reproduction

```sh
npx vitest --clearScreen=false

file:///…/node_modules/cac/dist/index.mjs:400
          throw new CACError(`Unknown option \`${name.length > 1 ? `--${name}` : `-${name}`}\``);
                ^

CACError: Unknown option `--clearScreen`
    at Command.checkUnknownOptions (file:///…/node_modules/cac/dist/index.mjs:400:17)
    at CAC.runMatchedCommand (file:///…/node_modules/cac/dist/index.mjs:598:13)
    at CAC.parse (file:///…/node_modules/cac/dist/index.mjs:537:12)
    at file:///…/node_modules/vitest/dist/cli.js:72:7
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async main (file:///…/node_modules/vitest/dist/cli-wrapper.js:45:5)

Node.js v20.11.0
```

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
All supported options are listed [here](https://vitest.dev/guide/cli.html) and [here](https://vitest.dev/config/). As a rule, we don't support options outside of `test` property.

**Comment by paularmstrong** [comment]
Okay, I get that, but can we reconsider? It would be helpful in certain scenarios, like pre-commit hooks, to specifically not clear the screen.

**Comment by hi-ogawa** [comment]
Sometimes I also wanted to disable clearing screen and keep old logs (mostly for debugging), but I didn't know that Vitest was checking Vite's `clearScreen` flags for this beheavior:

https://github.com/vitest-dev/vitest/blob/7d9b1fb02338beef048487ef07f6083aa5559106/packages/vitest/src/node/logger.ts#L65-L74

I think it would be nice if this could be quickly disabled from CLI directly.

**Comment by MangelMaxime** [comment]
`clearScreen` is indeed useful for people that use a transpiler to generate JavaScript.

Without this option, we need to spawn 2 terminals so we can see the output of the transpiler (for debug, compilation errors, etc.) and also the tests results.
