### ISSUE TITLE
vitest fails when running a very simple test

### ISSUE THREAD

**Issue by gabriel-naressi** [vitest-dev/vitest#5275]
### Describe the bug

I have a lib with the following structure:

My package.json

```json
{
  "name": "@bee-ui/bee-ui",
  "version": "1.2.4",
  "type": "module",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/bee-ui.js",
      "require": "./dist/bee-ui.umd.cjs"
    }
  },
  "main": "./dist/bee-ui.umd.cjs",
  "types": "./dist/index.d.ts",
  "files": [
    "dist"
  ],
  "scripts": {
    "build": "yarn build:clean && tsc && vite build",
    "build-storybook": "storybook build",
    "build:clean": "rimraf dist",
    "clean": "rimraf node_modules dist coverage",
    "lint": "eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0",
    "lint:fix": "prettier --write \"./**/*.{ts,tsx}\" && eslint . --ext .ts,.tsx --fix",
    "publish": "yarn npm publish",
    "storybook": "storybook dev -p 6006",
    "test": "vitest run",
    "test:watch": "vitest"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.5.1",
    "@fortawesome/free-solid-svg-icons": "^6.5.1",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "lodash.isempty": "^4.4.0",
    "lodash.merge": "^4.6.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "styled-components": "^6.1.8"
  },
  "devDependencies": {
    "@storybook/addon-essentials": "^7.6.12",
    "@storybook/addon-interactions": "^7.6.12",
    "@storybook/addon-links": "^7.6.12",
    "@storybook/addon-onboarding": "^1.0.11",
    "@storybook/blocks": "^7.6.12",
    "@storybook/react": "^7.6.12",
    "@storybook/react-vite": "^7.6.12",
    "@storybook/test": "^7.6.12",
    "@testing-library/dom": "^9.3.4",
    "@testing-library/jest-dom": "^6.4.1",
    "@testing-library/react": "^14.2.1",
    "@testing-library/user-event": "^14.5.2",
    "@types/jest": "^29.5.12",
    "@types/jsdom": "^21.1.6",
    "@types/lodash.isempty": "^4.4.9",
    "@types/lodash.merge": "^4",
    "@types/react": "^18.2.51",
    "@types/react-dom": "^18.2.18",
    "@types/styled-components": "^5.1.34",
    "@typescript-eslint/eslint-plugin": "^6.20.0",
    "@typescript-eslint/parser": "^6.20.0",
    "@vitejs/plugin-react": "^4.2.1",
    "eslint": "^8.56.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.5",
    "eslint-plugin-storybook": "^0.6.15",
    "jest-styled-components": "^7.2.0",
    "jsdom": "^23.2.0",
    "prettier": "^3.2.4",
    "rimraf": "^5.0.5",
    "storybook": "^7.6.12",
    "typescript": "^5.3.3",
    "vite": "^5.0.12",
    "vite-plugin-dts": "^3.7.2",
    "vitest": "^1.2.2"
  },
  "peerDependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "packageManager": "yarn@4.0.2",
  "engines": {
    "node": ">=20.11.0",
    "npm": ">=10.2.4"
  }
}
```

My `vite.config.ts` file:

```typescript

import { join, resolve } from "path";
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import dts from "vite-plugin-dts";

import { UserConfigExport } from "vitest/config";
import { compilerOptions } from "./tsconfig.json";

const sanitizeAlias = (val: string): string => val.replace("/*", "");

const aliasWithAbsolutePath = Object.entries(compilerOptions.paths).reduce(
  (acc: { [key: string]: string }, [key, value]) => {
    acc[sanitizeAlias(key)] = sanitizeAlias(join(__dirname, value[0]));
    return acc;
  },
  {} as { [key: string]: string },
);

const config: UserConfigExport = {
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./src/tests/setup.ts"],
  },
  build: {
    lib: {
      entry: resolve(__dirname, "src/main.tsx"),
      name: "BeeUi",
      fileName: "bee-ui",
    },
    rollupOptions: {
      external: ["react", "react-dom", "styled-components"],
      output: {
        globals: {
          react: "React",
          "styled-components": "styled",
          "react-dom": "ReactDOM",
        },
      },
    },
  },
  plugins: [react(), dts({ rollupTypes: true })],
  resolve: {
    alias: aliasWithAbsolutePath,
  },
};

export default defineConfig(config);
```

My `tsconfig.json`:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "declaration": true,
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,

    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",

    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "paths": {
      "@tests/*": [
        "src/tests/*"
      ],
      "@themes/*": [
        "src/themes/*"
      ]
    }
  },
  "include": ["src", "vite.config.ts", "tsconfig.json"],
  "references": [{ "path": "./tsconfig.node.json" }],
  "exclude": ["node_modules", "dist"]
}
```

My `tsconfig.node.json`

```json
{
  "compilerOptions": {
    "composite": true,
    "skipLibCheck": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts", "tsconfig.json"]
}
```

My `main.tsx`

```typescript
export { Typography } from "./atoms/typography";
```

My `Typography` component:

```typescript
import { ReactNode } from "react";
import styled from "styled-components";

export type Variants = "h1";

export interface TypographyProps {
  variant: Variants;
  children: ReactNode;
  className?: string;
}

const H1 = styled.h1`
  color: ${({ theme }) => theme.color.neutral.dark};
  font-size: 32px;
  line-height: 40px;
  font-weight: 700;
`;

const variantMapping = {
  h1: H1,
};

export const Typography = ({
  variant = "h2",
  children,
  className,
}: TypographyProps) => {
  const Component = variantMapping[variant];
  return <Component className={className}>{children}</Component>;
};
```

### Reproduction

When publishing this library to a private repository, I tried to create a test like this:

```javascript
import App from './App'
import { render, screen, userEvent } from './utils/test-utils'
import { Typography } from "@bee-ui/bee-ui";

describe('Simple working test', () => {
  test("should not render when user is not master", async () => {
    render(<Typography variant="h1">H1 content</Typography>);
    expect(screen.getByText(/h1 content/i)).toBeInTheDocument();
  });
})

```

`Typography` is my react component that i want to test.

Even using the example environment from the vitest documentation: https://github.com/vitest-dev/vitest/tree/main/examples/react-testing-lib, this test fails with a generic message: 

```
TypeError: e.h1 is not a function
    at file:///vitest/examples/react-testing-lib/node_modules/@bee-ui/bee-ui/dist/main.js:1:84
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at VitestExecutor.interopedImport (file://vitest/examples/react-testing-lib/node_modules/vite-node/dist/client.mjs:383:28)
    at VitestExecutor.directRequest (file://vitest/examples/react-testing-lib/node_modules/vite-node/dist/client.mjs:253:24)
    at VitestExecutor.cachedRequest (file://vitest/examples/react-testing-lib/node_modules/vite-node/dist/client.mjs:189:14)
    at VitestExecutor.dependencyRequest (file://vitest/examples/react-testing-lib/node_modules/vite-node/dist/client.mjs:233:12)
    at vitest/examples/react-testing-lib/src/App.test.tsx:4:31
    at VitestExecutor.runModule (file:///vitest/examples/react-testing-lib/node_modules/vite-node/dist/client.mjs:362:5)
```

### System Info

```shell
TypeError: e.h1 is not a function
    at file:///vitest/examples/react-testing-lib/node_modules/@bee-ui/bee-ui/dist/main.js:1:84
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at VitestExecutor.interopedImport (file://vitest/examples/react-testing-lib/node_modules/vite-node/dist/client.mjs:383:28)
    at VitestExecutor.directRequest (file://vitest/examples/react-testing-lib/node_modules/vite-node/dist/client.mjs:253:24)
    at VitestExecutor.cachedRequest (file://vitest/examples/react-testing-lib/node_modules/vite-node/dist/client.mjs:189:14)
    at VitestExecutor.dependencyRequest (file://vitest/examples/react-testing-lib/node_modules/vite-node/dist/client.mjs:233:12)
    at vitest/examples/react-testing-lib/src/App.test.tsx:4:31
    at VitestExecutor.runModule (file:///vitest/examples/react-testing-lib/node_modules/vite-node/dist/client.mjs:362:5)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
It's a bit hard to digest the issue from that long description. Could you move your code into a github repo or provide code on stackblitz?

**Comment by gabriel-naressi** [comment]
@hi-ogawa ooh ok, i can do this! Give me a few minutes

**Comment by gabriel-naressi** [comment]
@hi-ogawa There it is: https://stackblitz.com/edit/vitejs-vite-moqufx?file=src%2Fatoms%2F__tests__%2Ftypography.spec.tsx

**Comment by gabriel-naressi** [comment]
@hi-ogawa one additional piece of information that I forgot to add is that this problem only happens when I run the test. When I manually test the application, this `Typography` component renders correctly without any problems.
