### ISSUE TITLE
Address already in use :::24678 in monorepo

### ISSUE THREAD

**Issue by openscript** [vitest-dev/vitest#5577]
### Describe the bug

When starting vitest inside a monorepo configuration with PNPM this error occurs:

```
Error: listen EADDRINUSE: address already in use :::24678
    at Server.setupListenHandle [as _listen2] (node:net:1872:16)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2008:7)
    at Object.listen (file:///workspaces/timelet/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7_terser@5.29.2/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:61166:27)
    at file:///workspaces/timelet/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7_terser@5.29.2/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:65901:51
    at Array.forEach (<anonymous>)
    at Object.listen (file:///workspaces/timelet/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7_terser@5.29.2/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:65901:22)
    at _createServer (file:///workspaces/timelet/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7_terser@5.29.2/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:65129:17)
    at createViteServer (file:///workspaces/timelet/node_modules/.pnpm/vitest@1.5.0_@types+node@20.12.7_terser@5.29.2/node_modules/vitest/dist/vendor/cac.qnW6GNL2.js:10969:18) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 24678
}
```

I'm not sure if this also happens because I'm running Vitest inside a dev container. Except `vitest.workspace.ts` I don't have any Vitest related configuration.

### Reproduction

1. Clone https://github.com/timelet/timelet/tree/try/vitest
2. Checkout branch `try/vitest` 
3. Open in VSCode dev container
4. Run `pnpm install`
5. Run `pnpm test`

### System Info

```shell
System:
    OS: Linux 6.8 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 15.76 GB / 31.07 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.10.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 9.0.4 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    vitest: ^1.5.0 => 1.5.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by openscript** [comment]
I've added a `vitest.config.ts` to all packages with:

```
import { defineConfig } from "vitest/config";

export default defineConfig({
  server: {
    hmr: {
      protocol: "ws",
      host: "localhost",
    },
  },
});
```

That seems to fix the issue.
