### ISSUE TITLE
Resource Busy Or Locked Error

### ISSUE THREAD

**Issue by irv075** [vitest-dev/vitest#5740]
### Describe the bug

The extension throws a `resource busy or locked` exception intermittently. It seems to be trying to access files in the root of the C drive - usually `c:\DumpStack.log.tmp` or `c:\hiberfil.sys` (if dumpstack logging has been disabled).

After the error has been thrown I have to disable then re-enable the extension to get it running again - it will then fail again after an amount of time ranging from a few seconds to 15 minutes.

OS: Windows 10
VS Code:1.88.1
Vitest Extension: 0.8.6

### Reproduction

No special reproduction required, the exception is thrown even when no tests are being ran, just having the extension enabled for a period of time.

### Output

```shell
[INFO 10:26:05 AM] [v0.8.6] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 10:26:06 AM] [API] Running Vitest: v1.5.0 (vitest.config.ts)
[INFO 10:26:06 AM] [API] Starting Vitest process with Node.js: C:\Program Files\nodejs\node.EXE
[INFO 10:26:09 AM] [API] Vitest process 454476 created
[INFO 10:26:29 AM] [API] Vitest process 454476 closed successfully
[INFO 10:26:29 AM] [API] Running Vitest: v1.5.0 (vitest.config.ts)
[INFO 10:26:29 AM] [API] Starting Vitest process with Node.js: C:\Program Files\nodejs\node.EXE
[INFO 10:26:31 AM] [API] Vitest process 521280 created
[Worker] node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///C:/Repositories/testapp/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:46060:10)
    at NodeFsHandler._boundHandleError (file:///C:/Repositories/testapp/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:44533:43)
    at ReaddirpStream.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'C:\\hiberfil.sys'
}

Node.js v20.11.0
```

### Version

0.8.6

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Btw, can you provide "System Info" in a comment? You can simply run `npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers` like we have on issue template https://github.com/vitest-dev/vitest/issues/new?assignees=&labels=pending+triage&projects=&template=bug_report.yml

**Comment by hi-ogawa** [comment]
@patak-dev It looks like the issue of `/@react-refresh` not following `\0` convention is brought up in https://github.com/vitejs/vite/pull/15299. Does Vite team have any plan to change it in the future?

**Comment by irv075** [comment]
> Btw, can you provide "System Info" in a comment? You can simply run `npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers` like we have on issue template https://github.com/vitest-dev/vitest/issues/new?assignees=&labels=pending+triage&projects=&template=bug_report.yml

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 15.24 GB / 31.64 GB

  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD

  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.19041.3636
    
  npmPackages:
    @vitejs/plugin-react: 4.2.1 => 4.2.1
    @vitest/coverage-v8: ^1.5.0 => 1.5.0
    @vitest/ui: ^1.5.0 => 1.5.0
    vite: ^5.2.10 => 5.2.10
    vitest: ^1.5.0 => 1.5.0

**Comment by nistre** [comment]
Do you have `"nx": {}` in your root package.json.  I started encountering this issue when I added the `nx` to the root package.json and the error goes away when I:
- Remove the `nx`
- Run `npm cache clear --force`
- Rerun my `npm run build` which runs: `npx nx run-many -t build,test,lint --exclude=import-tests --configuration=production`

With my obvious connection to nx, I'm 1.) not sure if it would be nx or a vite at fault and 2.) If it is related to this issue

- System:
    - OS: Windows 10 10.0.19045
    - CPU: (24) x64 12th Gen Intel(R) Core(TM) i7-12850HX
    - Memory: 14.70 GB / 31.69 GB
 - Binaries:
     - Node: 18.20.4 - C:\Program Files\nodejs\node.EXE
     - npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
- Browsers:
    - Edge: Chromium (126.0.2592.102)
    - Internet Explorer: 11.0.19041.4355
- npmPackages:
    - @vitest/ui: ^1.3.1 => 1.6.0
    - vite: ^5.0.11 => 5.3.1
    - vitest: ^1.2.1 => 1.6.0

**Comment by irv075** [comment]
> Do you have `"nx": {}` in your root package.json

No, we dont use `nx` at all in this project.

**Comment by meindertduin** [comment]
As of today, I seem to have a similar issues too on Windows.

Node version 18.20.5
Npm packages:
    "vite": "^5.4.6",
    "vitest": "^2.1.3",
    "@vitejs/plugin-vue": "^4.5.2",
    "@vitest/coverage-v8": "^2.1.3",
    "@vitest/ui": "^2.1.3",

On the (Windows) build agent I sometimes get the following error:
```
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: EBUSY: resource busy or locked, open 'C:\Windows\SERVIC~1\NETWOR~1\AppData\Local\Temp\R41OiOhVzrOL3LoAhkRN9\web\40b9f1f37d5bd759c353e90078138580f67eb091'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

This error is thrown after it's done with running the tests, and I presume vitest is trying to cleanup its temp files?
