### ISSUE TITLE
[2.1.0] TypeError: allTestFiles.filter is not a function

### ISSUE THREAD

**Issue by JCQuintas** [vitest-dev/vitest#6516]
### Describe the bug

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Startup Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: allTestFiles.filter is not a function
    at config (file:///Users/dev/mui/mui-x/node_modules/.pnpm/@vitest+browser@2.0.5_playwright@1.44.1_typescript@5.5.4_vitest@2.1.1/node_modules/@vitest/browser/dist/index.js:2162:47)
    at async runConfigHook (file:///Users/dev/mui/mui-x/node_modules/.pnpm/vite@5.3.4_@types+node@20.16.5_terser@5.27.0/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:67015:19)
    at async resolveConfig (file:///Users/dev/mui/mui-x/node_modules/.pnpm/vite@5.3.4_@types+node@20.16.5_terser@5.27.0/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:66466:12)
    at async _createServer (file:///Users/dev/mui/mui-x/node_modules/.pnpm/vite@5.3.4_@types+node@20.16.5_terser@5.27.0/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:63050:18)
    at async createBrowserServer (file:///Users/dev/mui/mui-x/node_modules/.pnpm/@vitest+browser@2.0.5_playwright@1.44.1_typescript@5.5.4_vitest@2.1.1/node_modules/@vitest/browser/dist/index.js:2501:16)
    at async WorkspaceProject.initBrowserServer (file:///Users/dev/mui/mui-x/node_modules/.pnpm/vitest@2.1.1_@types+node@20.16.5_@vitest+browser@2.0.5_jsdom@24.1.3_msw@2.4.4_typescript@5.5.4__terser@5.27.0/node_modules/vitest/dist/chunks/cli-api.BKkmK21J.js:9483:21)
    at async WorkspaceProject.setServer (file:///Users/dev/mui/mui-x/node_modules/.pnpm/vitest@2.1.1_@types+node@20.16.5_@vitest+browser@2.0.5_jsdom@24.1.3_msw@2.4.4_typescript@5.5.4__terser@5.27.0/node_modules/vitest/dist/chunks/cli-api.BKkmK21J.js:9549:5)
    at async configureServer (file:///Users/dev/mui/mui-x/node_modules/.pnpm/vitest@2.1.1_@types+node@20.16.5_@vitest+browser@2.0.5_jsdom@24.1.3_msw@2.4.4_typescript@5.5.4__terser@5.27.0/node_modules/vitest/dist/chunks/cli-api.BKkmK21J.js:9028:9)
    at async _createServer (file:///Users/dev/mui/mui-x/node_modules/.pnpm/vite@5.3.4_@types+node@20.16.5_terser@5.27.0/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:63372:20)
    at async createViteServer (file:///Users/dev/mui/mui-x/node_modules/.pnpm/vitest@2.1.1_@types+node@20.16.5_@vitest+browser@2.0.5_jsdom@24.1.3_msw@2.4.4_typescript@5.5.4__terser@5.27.0/node_modules/vitest/dist/chunks/cli-api.BKkmK21J.js:9050:18)



 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

While working on this PR: https://github.com/mui/mui-x/pull/14508

Tests run normally on `2.0.5`

Upgrade vitest to 2.1.0, the error will appear. 

If you remove the `browser` section in the config, it works. I don't know exactly what causes it though, as I couldn't reproduce in a smaller repo.

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 245.22 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.10.0 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  Browsers:
    Brave Browser: 127.1.68.137
    Chrome: 128.0.6613.138
    Safari: 17.6
  npmPackages:
    @vitejs/plugin-react: ^4.3.1 => 4.3.1 
    @vitest/browser: ^2.0.5 => 2.0.5 
    vitest: 2.1.1 => 2.1.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JCQuintas** [comment]
nevermind, had to update @vitest/browser 😓
