### ISSUE TITLE
`import.meta.resolve` is broken in vite-node, despite working in node

### ISSUE THREAD

**Issue by GauBen** [vitest-dev/vitest#6953]
### Describe the bug

Given an `index.mjs` file with the following line of code:

```ts
console.log(import.meta.resolve("./index.mjs"));
```

It works properly when running `node index.mjs`, but throws an error when running in vite-node `npx vite-node index.mjs`: `TypeError: __vite_ssr_import_meta__.resolve is not a function`

### Reproduction

1. `mkdir repro && cd $_`
2. `echo 'console.log(import.meta.resolve("./index.mjs"));' > index.mjs`
3. `node index.mjs` will print `file://.../repro/index.mjs`
4. `npx vite-node index.mjs` will print

```
Need to install the following packages:
vite-node@2.1.5
Ok to proceed? (y)

/home/gautier/repro/index.mjs:1
'use strict';async (__vite_ssr_import__,__vite_ssr_dynamic_import__,__vite_ssr_exports__,__vite_ssr_exportAll__,__vite_ssr_import_meta__,require,exports,module,__filename,__dirname)=>{{console.log(__vite_ssr_import_meta__.resolve("./index.mjs"));

                                                                                                      ^

TypeError: __vite_ssr_import_meta__.resolve is not a function
    at /home/gautier/repro/index.mjs:1:25
    at ViteNodeRunner.runModule (file:///home/gautier/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:399:11)
    at ViteNodeRunner.directRequest (file:///home/gautier/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:381:16)
    at ViteNodeRunner.cachedRequest (file:///home/gautier/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:206:14)
    at ViteNodeRunner.executeFile (file:///home/gautier/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/client.mjs:169:12)
    at CAC.run (file:///home/gautier/.npm/_npx/f2342a4b64a2bc92/node_modules/vite-node/dist/cli.mjs:99:5)

Node.js v20.18.0
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 7 4800HS with Radeon Graphics
    Memory: 3.52 GB / 7.47 GB
    Container: Yes
    Shell: 5.9 - /home/linuxbrew/.linuxbrew/bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.pkgx/nodejs.org/v20.18.0/bin/node
    npm: 10.9.1 - ~/.pkgx/npmjs.com/v10.9.1/bin/npm
    vite-node: 2.1.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
There was some discussions in the past (and my attempt https://github.com/vitest-dev/vitest/pull/5188), but unfortunately we cannot implement it properly on vite-node / Vitest currently.

**Comment by GauBen** [comment]
Thanks @hi-ogawa! By any chance, is Vite 6 bringing the team one step closer to implementing import.meta.resolve?

**Comment by sheremet-va** [comment]
> Thanks @hi-ogawa! By any chance, is Vite 6 bringing the team one step closer to implementing import.meta.resolve?

No, `import.meta.resolve` is still not available even in Vite Module Runner

**Comment by aklinker1** [comment]
I was able to work around this, but it's not pretty. But my tests for functions that rely on `import.meta.resolve` seem to be working just fine.

```ts
// vitest.config.ts
export default defineConfig({
  test: {
    setupFiles: ["./vitest.setup.ts"],
  },
});
```

```ts
// vitest.setup.ts
import { vi } from 'vitest';
import { createRequire } from 'node:module';

vi.stubGlobal('globalCreateRequire', createRequire);
```

```ts
// source file that uses `import.meta.resolve`...

// ...

// At the very bottom:
if (typeof __vite_ssr_import_meta__ !== 'undefined') {
  __vite_ssr_import_meta__.resolve = (path: string) =>
    'file://' + globalCreateRequire(import.meta.url).resolve(path);
}
```

We create `globalCreateRequire` in the setup file so we don't have to add an import for `node:module` in the source-code.

You have to put that mess in every source file that uses `import.meta.resolve`, because it seems like the `__vite_ssr_import_meta__` is defined per-file.

**Comment by JounQin** [comment]
@zanminkian That prefers commonjs entry.

**Comment by dcleao** [comment]
So unfortunate :-) Are there any news to this? Thank you

**Comment by OnlyWick** [comment]
A simple mock implementation for ESM.

```ts
// something.ts
export const importMetaResolve = (...args: Parameters<ImportMeta['resolve']>) => {
  if (typeof import.meta.resolve !== 'function' && process.env.VITEST === 'true') {
    // patch for vitest
    return pathToFileURL(args[0]).href
  }

  return import.meta.resolve(...args)
}

const xx = importMetaResolve(...)
```

```ts
// something.spec.ts
vi.mock('./something.ts', async (importOriginal) => {
  const original = await importOriginal()
  const isTransformed = (a: string) => a.startsWith('file://')

  return {
    ...(original as Record<string, unknown>),
    importMetaResolve: vi.fn().mockImplementation((a) => (isTransformed(a) ? a : `file://${a}`)),
  }
})
```

**Comment by michaelfaith** [comment]
I'm not sure I'd call that just a mock.  It's creating a _runtime_ wrapper just to polyfill a gap in the testing framework, and then using a mock at test time to transform the result.

**Comment by OnlyWick** [comment]
> I'm not sure I'd call that just a mock. It's creating a _runtime_ wrapper just to polyfill a gap in the testing framework, and then using a mock at test time to transform the result.

Yeap, this is indeed a polyfill, but it needs `vi.mock` to be useful. The goal is to make the test pass first, and then wait for `vite` to support `import.meta.resolve`
