### ISSUE TITLE
`vitest.config.ts` with ternary condition relying on env var deleted the entire repo

### ISSUE THREAD

**Issue by thisisxvr** [vitest-dev/vitest#918]
### Describe the bug

Running `vitest run --coverage --reporter=junit` deleted all files in the directory including `.git`.

The cause appears to be the ternary condition I have in `vitest.config.ts` that checks an environment variable:
```
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    root: "src",
    setupFiles: ["src/tests/setup.ts"],
    reporters: ["default", "junit"],
    outputFile: "coverage/junit.xml",
    coverage: {
      include: ["src"],
      exclude: [
        "src/tests",
        "src/types",
        "src/datasources/cosmos/defaults.ts",
        "**/*/types.ts",
        "**/*/operations.ts",
        "**/*/*.graphql.ts",
        "**/*/*.test.ts",
        "**/*/__test__",
      ],
      reportsDirectory: process.env.CI ? "coverage" : undefined,
      reporter: process.env.CI ? "cobertura" : undefined,
    },
  },
});
```

Running the command recursively deleted the entire repo and logged the following output:
```
❯ npm run test:unit

> powercredit@0.1.0 test:unit
> vitest run --coverage --reporter=junit

 MISSING DEP  Can not find dependency 'c8'


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/thisisxvr/powercredit/node_modules/vitest/dist/vendor-index.665a6ba4.js' imported from /Users/thisisxvr/powercredit/node_modules/vitest/dist/chunk-utils-base.68f100c1.js
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:308:11)
    at moduleResolve (internal/modules/esm/resolve.js:731:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at ensurePackageInstalled (file:///Users/thisisxvr/powercredit/node_modules/vitest/dist/chunk-utils-base.68f100c1.js:179:19) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

### Reproduction

```
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    root: "src",
    setupFiles: ["src/tests/setup.ts"],
    reporters: ["default", "junit"],
    outputFile: "coverage/junit.xml",
    coverage: {
      include: ["src"],
      exclude: [
        "src/tests",
        "src/types",
        "src/datasources/cosmos/defaults.ts",
        "**/*/types.ts",
        "**/*/operations.ts",
        "**/*/*.graphql.ts",
        "**/*/*.test.ts",
        "**/*/__test__",
      ],
      reportsDirectory: process.env.CI ? "coverage" : undefined,
      reporter: process.env.CI ? "cobertura" : undefined,
    },
  },
});
```

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.32 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.asdf/installs/nodejs/14.18.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.4.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 89.0.2
    Firefox Developer Edition: 98.0
    Safari: 15.0
  npmPackages:
    vitest: 0.5.9 => 0.5.9
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jrobeson** [comment]
you don't describe what env variables you have set when you run it. Are you sure the bug isn't just the `undefined` ?

And it's also more likely that passing `undefined` to `reportsDirectory` is what's really causing the problem.
